import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'
import postgres from 'https://deno.land/x/postgresjs@v3.4.7/mod.js'

const URL=Deno.env.get('SUPABASE_URL')!
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const DB=Deno.env.get('SUPABASE_DB_URL')!
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})
const sql=postgres(DB,{prepare:false,max:2})
const providers=['google','meta','tiktok','linkedin']
const origins=new Set(['https://app.listiaapp.com','https://listia-pwa.pages.dev'])
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':origins.has(o)?o:'https://app.listiaapp.com','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, apikey, content-type','vary':'Origin'}}
function out(r:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(r),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function ready(c:any){if(!c||c.status!=='connected')return false;const m=c.metadata||{},sc=(c.granted_scopes||[]).map((x:string)=>String(x).toLowerCase());if(c.provider==='google')return sc.some((x:string)=>x.includes('datamanager'))&&Boolean(m.google_ads_customer_id)&&Boolean(Object.values(m.conversion_actions||{}).find(Boolean));if(c.provider==='meta')return Boolean(m.dataset_id||m.pixel_id);if(c.provider==='tiktok')return Boolean(m.advertiser_id)&&Boolean(m.event_source_id||m.pixel_id);if(c.provider==='linkedin')return Boolean(m.sponsored_account_id)&&Boolean(Object.values(m.conversion_ids||{}).find(Boolean));return false}
function safeMeta(c:any){const m=c?.metadata||{};if(c?.provider==='google')return{account_id:m.google_ads_customer_id||null,configured_actions:Object.keys(m.conversion_actions||{}).filter(k=>m.conversion_actions[k])};if(c?.provider==='meta')return{dataset_id:m.dataset_id||m.pixel_id||null,dataset_name:m.dataset_name||null,test_mode:Boolean(m.test_event_code),min_quality_score:m.min_quality_score??null};if(c?.provider==='tiktok')return{advertiser_id:m.advertiser_id||null,event_source_id:m.event_source_id||m.pixel_id||null,pixel_name:m.pixel_name||null,test_mode:Boolean(m.test_event_code),min_quality_score:m.min_quality_score??null};if(c?.provider==='linkedin')return{account_id:m.sponsored_account_id||null,configured_actions:Object.keys(m.conversion_ids||{}).filter(k=>m.conversion_ids[k]),min_quality_score:m.min_quality_score??null};return{}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,{error:'method_not_allowed'},405);try{const o=req.headers.get('origin')||'';if(o&&!origins.has(o))return out(req,{error:'origin_not_allowed'},403);const auth=req.headers.get('authorization')||'';if(!auth)return out(req,{error:'unauthorized'},401);const {data:{user}}=await admin.auth.getUser(auth.replace(/^Bearer\s+/i,''));if(!user)return out(req,{error:'unauthorized'},401);const b=await req.json().catch(()=>({})) as any,org=String(b.organization_id||'');if(!/^[0-9a-f-]{36}$/i.test(org))return out(req,{error:'organization_required'},400);const {data:member}=await admin.from('organization_members').select('status').eq('organization_id',org).eq('user_id',user.id).eq('status','active').maybeSingle();if(!member)return out(req,{error:'forbidden'},403);
const conns=await sql`select id,provider,status,display_name,granted_scopes,metadata,connected_at,last_error from public.integration_connections where organization_id=${org}::uuid and provider=any(${providers}::text[]) order by provider`;
const queue=await sql`select p.platform,s.delivery_status,count(*)::int total from public.conversion_signals s cross join lateral unnest(s.platforms) p(platform) where s.organization_id=${org}::uuid and p.platform=any(${providers}::text[]) group by p.platform,s.delivery_status`;
const deliveries=await sql`select platform,status,count(*)::int total,max(delivered_at) last_delivered_at,max(updated_at) last_updated_at from private.conversion_signal_deliveries where organization_id=${org}::uuid group by platform,status`;
const last=await sql`select distinct on(platform) platform,status,last_http_status,last_error,updated_at,delivered_at from private.conversion_signal_deliveries where organization_id=${org}::uuid order by platform,updated_at desc`;
const byProvider:any={};for(const p of providers){const c=conns.find((x:any)=>x.provider===p);const q:any={};for(const x of queue.filter((x:any)=>x.platform===p))q[x.delivery_status]=Number(x.total);const d:any={};for(const x of deliveries.filter((x:any)=>x.platform===p))d[x.status]={total:Number(x.total),last_delivered_at:x.last_delivered_at,last_updated_at:x.last_updated_at};const l=last.find((x:any)=>x.platform===p);byProvider[p]={provider:p,connected:Boolean(c&&c.status==='connected'),ready:ready(c),connection_status:c?.status||'not_connected',display_name:c?.display_name||null,connected_at:c?.connected_at||null,connection_error:c?.last_error?String(c.last_error).slice(0,240):null,config:safeMeta(c),queue:q,deliveries:d,last_delivery:l?{status:l.status,http_status:l.last_http_status,error:l.last_error?String(l.last_error).slice(0,240):null,updated_at:l.updated_at,delivered_at:l.delivered_at}:null}}
const totals={queued:queue.reduce((n:number,x:any)=>n+(['pending','processing','partial','failed','waiting'].includes(x.delivery_status)?Number(x.total):0),0),sent:deliveries.filter((x:any)=>x.status==='sent').reduce((n:number,x:any)=>n+Number(x.total),0),failed:deliveries.filter((x:any)=>x.status==='failed').reduce((n:number,x:any)=>n+Number(x.total),0),suppressed:deliveries.filter((x:any)=>x.status==='suppressed').reduce((n:number,x:any)=>n+Number(x.total),0)};return out(req,{ok:true,organization_id:org,providers:providers.map(p=>byProvider[p]),totals,generated_at:new Date().toISOString()})}catch(e){console.error('conversion-integrations-status',e);return out(req,{error:'internal_error'},500)}})
