import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'
const U=Deno.env.get('SUPABASE_URL')!,S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const allowed=new Set(['https://app.listiaapp.com','https://listia-pwa.pages.dev','http://localhost','http://127.0.0.1']);
const cors=(o:string)=>({'access-control-allow-origin':allowed.has(o)?o:'https://app.listiaapp.com','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'authorization,apikey,content-type','vary':'Origin'});
const reply=(o:string,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(o),'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
Deno.serve(async req=>{const o=req.headers.get('origin')||'';if(req.method==='OPTIONS')return allowed.has(o)?new Response(null,{status:204,headers:cors(o)}):new Response(null,{status:403});if(req.method!=='POST')return reply(o,{error:'method_not_allowed'},405);if(o&&!allowed.has(o))return reply(o,{error:'origin_not_allowed'},403);const jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return reply(o,{error:'unauthorized'},401);const db=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});const {data:ud,error:ue}=await db.auth.getUser(jwt);const user=ud?.user;if(ue||!user)return reply(o,{error:'unauthorized'},401);let b:any;try{b=await req.json()}catch{return reply(o,{error:'invalid_json'},400)}const oid=String(b.organization_id||''),leadId=String(b.lead_id||''),action=String(b.action||'');if(!oid||!leadId||!action)return reply(o,{error:'missing_fields'},400);const {data:member}=await db.from('organization_members').select('role,status').eq('organization_id',oid).eq('user_id',user.id).eq('status','active').maybeSingle();if(!member)return reply(o,{error:'forbidden'},403);const {data:lead}=await db.from('leads').select('id,organization_id,assigned_user_id').eq('id',leadId).eq('organization_id',oid).maybeSingle();if(!lead)return reply(o,{error:'lead_not_found'},404);const admin=['owner','admin'].includes(String(member.role));
if(action==='add_note'){const body=String(b.body||'').trim().slice(0,4000);if(!body)return reply(o,{error:'note_required'},400);const {data,error}=await db.from('lead_notes').insert({organization_id:oid,lead_id:leadId,author_user_id:user.id,body}).select('id,body,author_user_id,created_at').single();if(error)return reply(o,{error:'write_failed'},500);await db.from('lead_events').insert({organization_id:oid,lead_id:leadId,event_type:'note_added',source:'listia',metadata:{note_id:data.id},occurred_at:new Date().toISOString()});await db.from('leads').update({last_activity_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',leadId);return reply(o,{ok:true,note:data})}
if(action==='add_task'){const title=String(b.title||'').trim().slice(0,240);if(!title)return reply(o,{error:'title_required'},400);let assigned=String(b.assigned_user_id||user.id);const {data:am}=await db.from('organization_members').select('user_id').eq('organization_id',oid).eq('user_id',assigned).eq('status','active').maybeSingle();if(!am)assigned=user.id;const due=typeof b.due_at==='string'&&b.due_at?new Date(b.due_at).toISOString():null;const {data,error}=await db.from('lead_tasks').insert({organization_id:oid,lead_id:leadId,title,status:'open',due_at:due,assigned_user_id:assigned,created_by:user.id}).select('id,title,status,due_at,assigned_user_id,created_at').single();if(error)return reply(o,{error:'write_failed'},500);await db.from('lead_events').insert({organization_id:oid,lead_id:leadId,event_type:'task_created',source:'listia',metadata:{task_id:data.id,title:data.title},occurred_at:new Date().toISOString()});return reply(o,{ok:true,task:data})}
if(action==='task_status'){const taskId=String(b.task_id||''),status=String(b.status||'');if(!taskId||!['done','cancelled','open'].includes(status))return reply(o,{error:'invalid_task_status'},400);const {data:task}=await db.from('lead_tasks').select('id,assigned_user_id,created_by').eq('id',taskId).eq('lead_id',leadId).eq('organization_id',oid).maybeSingle();if(!task)return reply(o,{error:'task_not_found'},404);if(!admin&&task.assigned_user_id!==user.id&&task.created_by!==user.id)return reply(o,{error:'forbidden'},403);const now=new Date().toISOString(),{error}=await db.from('lead_tasks').update({status,completed_at:status==='done'?now:null,updated_at:now}).eq('id',taskId);if(error)return reply(o,{error:'write_failed'},500);await db.from('lead_events').insert({organization_id:oid,lead_id:leadId,event_type:`task_${status}`,source:'listia',metadata:{task_id:taskId},occurred_at:now});return reply(o,{ok:true})}
if(action==='assign'){if(!admin)return reply(o,{error:'forbidden'},403);const assigned=String(b.assigned_user_id||'');if(assigned){const {data:am}=await db.from('organization_members').select('user_id').eq('organization_id',oid).eq('user_id',assigned).eq('status','active').maybeSingle();if(!am)return reply(o,{error:'invalid_assignee'},400)}const now=new Date().toISOString(),{error}=await db.from('leads').update({assigned_user_id:assigned||null,last_activity_at:now,updated_at:now}).eq('id',leadId).eq('organization_id',oid);if(error)return reply(o,{error:'write_failed'},500);await db.from('lead_events').insert({organization_id:oid,lead_id:leadId,event_type:'assigned',source:'listia',metadata:{assigned_user_id:assigned||null},occurred_at:now});return reply(o,{ok:true})}
return reply(o,{error:'unsupported_action'},400)});
