// Generated by LISTIA Marketplace Edge Proof Resync. This is a one-way SHA-256 hash, never a secret.
export const MARKETPLACE_EDGE_PROOF_SHA256 = '98c07e01ae204ae31a533024357b7c58d52f91f894e2ec9e8aabe861432be417'
