(() => {
  const SUPABASE='https://zvzafiarwerbuoaccnoz.supabase.co';
  const history=[];
  const locale=()=>document.documentElement.dataset.listiaLanguage||document.documentElement.lang||'en';
  const copy=()=>locale().toLowerCase().startsWith('es')?{title:'Habla con LISTIA',sub:'Atención con inteligencia artificial',ph:'Escribe tu pregunta…',send:'Enviar',hello:'Hola. Soy LISTIA. ¿Qué quieres saber sobre la plataforma, el marketplace o los planes?'}:{title:'Talk to LISTIA',sub:'AI customer service',ph:'Ask me anything…',send:'Send',hello:'Hi. I’m LISTIA. What would you like to know about the platform, marketplace, or plans?'};
  const css=`#listiaCsBtn{position:fixed;right:20px;bottom:20px;z-index:9998;width:62px;height:62px;border:0;border-radius:50%;cursor:pointer;background:radial-gradient(circle at 34% 26%,#fff 0 2%,#5fc4ff 5%,#6d39ff 38%,#ef48c9 72%,#2b133f 100%);box-shadow:0 0 0 5px rgba(124,60,255,.08),0 0 32px rgba(124,60,255,.48);color:#fff;font-size:26px}#listiaCsPanel{position:fixed;right:18px;bottom:94px;z-index:9999;width:min(390px,calc(100vw - 28px));height:min(560px,72vh);display:none;grid-template-rows:auto 1fr auto;background:rgba(9,10,16,.98);border:1px solid rgba(255,255,255,.12);border-radius:22px;box-shadow:0 28px 80px rgba(0,0,0,.46);overflow:hidden;backdrop-filter:blur(18px)}#listiaCsPanel.open{display:grid}.lcsHead{display:flex;justify-content:space-between;gap:14px;padding:16px 17px;border-bottom:1px solid rgba(255,255,255,.08)}.lcsHead strong{display:block;font:700 16px/1.2 Inter,system-ui;color:#fff}.lcsHead small{display:block;margin-top:3px;font:500 12px/1.3 Inter,system-ui;color:#9ca5bb}.lcsClose{border:0;background:#1c1e29;color:#fff;width:36px;height:36px;border-radius:50%;font-size:20px}.lcsMsgs{padding:14px;overflow:auto;display:flex;flex-direction:column;gap:10px}.lcsMsg{max-width:86%;padding:10px 12px;border-radius:15px;font:500 13px/1.45 Inter,system-ui;white-space:pre-wrap}.lcsMsg.ai{align-self:flex-start;background:#151824;color:#e8e9ef;border:1px solid rgba(255,255,255,.07)}.lcsMsg.me{align-self:flex-end;background:linear-gradient(135deg,#7b3cff,#953fff);color:#fff}.lcsForm{display:grid;grid-template-columns:1fr auto;gap:8px;padding:12px;border-top:1px solid rgba(255,255,255,.08)}.lcsForm input{min-width:0;border:1px solid rgba(255,255,255,.10);border-radius:13px;background:#11131b;color:#fff;padding:11px 12px;font:500 13px Inter,system-ui;outline:none}.lcsForm button{border:0;border-radius:13px;background:#7c3cff;color:#fff;padding:0 14px;font:700 12px Inter,system-ui}@media(max-width:600px){#listiaCsBtn{right:14px;bottom:14px}#listiaCsPanel{right:14px;bottom:88px;width:calc(100vw - 28px);height:64vh}}`;
  const style=document.createElement('style');style.textContent=css;document.head.append(style);
  const btn=document.createElement('button');btn.id='listiaCsBtn';btn.type='button';btn.setAttribute('aria-label','LISTIA AI');btn.textContent='✦';
  const panel=document.createElement('section');panel.id='listiaCsPanel';panel.setAttribute('aria-live','polite');
  panel.innerHTML=`<div class="lcsHead"><div><strong id="lcsTitle"></strong><small id="lcsSub"></small></div><button class="lcsClose" type="button" aria-label="Close">×</button></div><div class="lcsMsgs" id="lcsMsgs"></div><form class="lcsForm" id="lcsForm"><input id="lcsInput" maxlength="1800" autocomplete="off"><button id="lcsSend" type="submit"></button></form>`;
  document.body.append(btn,panel);
  const msgs=panel.querySelector('#lcsMsgs'),input=panel.querySelector('#lcsInput'),title=panel.querySelector('#lcsTitle'),sub=panel.querySelector('#lcsSub'),send=panel.querySelector('#lcsSend');
  const add=(text,who)=>{const d=document.createElement('div');d.className=`lcsMsg ${who}`;d.textContent=text;msgs.append(d);msgs.scrollTop=msgs.scrollHeight};
  const sync=()=>{const c=copy();title.textContent=c.title;sub.textContent=c.sub;input.placeholder=c.ph;send.textContent=c.send;if(!msgs.children.length)add(c.hello,'ai')};
  btn.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open')){sync();setTimeout(()=>input.focus(),40)}};panel.querySelector('.lcsClose').onclick=()=>panel.classList.remove('open');
  panel.querySelector('#lcsForm').addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';add(text,'me');history.push({role:'user',content:text});send.disabled=true;try{const r=await fetch(`${SUPABASE}/functions/v1/listia-public-chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,locale:locale(),history:history.slice(-8)})});const data=await r.json().catch(()=>({}));const reply=data.reply||(locale().toLowerCase().startsWith('es')?'No pude responder en este momento. Intenta nuevamente.':'I could not answer right now. Please try again.');add(reply,'ai');history.push({role:'assistant',content:reply});}catch{add(locale().toLowerCase().startsWith('es')?'Hubo un problema de conexión. Intenta nuevamente.':'There was a connection problem. Please try again.','ai')}finally{send.disabled=false;input.focus()}});
  window.addEventListener('listia:languagechange',sync);
  sync();
})();