// LISTIA commercial footer + global locale loader v1.2.0
(() => {
  const copy = {
    es:{rights:'© 2026 LISTIA. Todos los derechos reservados.',privacy:'Aviso de privacidad',terms:'Términos y condiciones'},
    en:{rights:'© 2026 LISTIA. All rights reserved.',privacy:'Privacy Notice',terms:'Terms & Conditions'},
    fr:{rights:'© 2026 LISTIA. Tous droits réservés.',privacy:'Avis de confidentialité',terms:'Conditions générales'},
    it:{rights:'© 2026 LISTIA. Tutti i diritti riservati.',privacy:'Informativa sulla privacy',terms:'Termini e condizioni'},
    'pt-BR':{rights:'© 2026 LISTIA. Todos os direitos reservados.',privacy:'Aviso de privacidade',terms:'Termos e condições'},
    de:{rights:'© 2026 LISTIA. Alle Rechte vorbehalten.',privacy:'Datenschutzhinweis',terms:'Nutzungsbedingungen'},
    'ar-AE':{rights:'© 2026 LISTIA. جميع الحقوق محفوظة.',privacy:'إشعار الخصوصية',terms:'الشروط والأحكام'},
    ru:{rights:'© 2026 LISTIA. Все права защищены.',privacy:'Уведомление о конфиденциальности',terms:'Условия использования'},
    he:{rights:'© 2026 LISTIA. כל הזכויות שמורות.',privacy:'הודעת פרטיות',terms:'תנאים והגבלות'},
    'zh-CN':{rights:'© 2026 LISTIA。保留所有权利。',privacy:'隐私声明',terms:'条款与条件'},
    ja:{rights:'© 2026 LISTIA. 無断転載を禁じます。',privacy:'プライバシー通知',terms:'利用規約'}
  };
  const normalize=v=>{const c=String(v||'en').toLowerCase();if(c.startsWith('pt'))return'pt-BR';if(c.startsWith('ar'))return'ar-AE';if(c.startsWith('es'))return'es';if(c.startsWith('fr'))return'fr';if(c.startsWith('it'))return'it';if(c.startsWith('de'))return'de';if(c.startsWith('ru'))return'ru';if(c.startsWith('he')||c.startsWith('iw'))return'he';if(c.startsWith('zh'))return'zh-CN';if(c.startsWith('ja'))return'ja';return'en'};
  function styles(){if(document.getElementById('listiaLegalFooterStyles'))return;const s=document.createElement('style');s.id='listiaLegalFooterStyles';s.textContent=`footer .wrap{align-items:flex-start}.listia-footer-main{display:flex;flex-direction:column;gap:7px;min-width:240px}.listia-footer-meta{display:flex;flex-wrap:wrap;align-items:center;gap:7px 14px}.listia-footer-links{display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center}.listia-footer-links a,.listia-powered a{font-size:.78rem;color:var(--muted);text-decoration:none;transition:color .15s ease}.listia-footer-links a:hover,.listia-powered a:hover{color:var(--paper)}.listia-powered{font-size:.78rem;color:var(--muted)}.listia-powered a{font-weight:600;color:var(--paper)}.listia-footer-right{display:flex;flex-direction:column;gap:7px;align-items:flex-end}@media(max-width:680px){footer .wrap{flex-direction:column;align-items:flex-start}.listia-footer-right{align-items:flex-start}}html[dir="rtl"] .listia-footer-right{align-items:flex-start}`;document.head.appendChild(s)}
  function ensure(){const footer=document.querySelector('footer .wrap');if(!footer)return null;let main=document.getElementById('listiaFooterMain');if(main)return main;const domain=Array.from(footer.children).find(n=>n.textContent.trim()==='listiaapp.com'),tag=document.getElementById('footerTagline');main=document.createElement('div');main.id='listiaFooterMain';main.className='listia-footer-main';main.innerHTML=`<span id="listiaFooterRights"></span><div class="listia-footer-meta"><nav class="listia-footer-links" aria-label="Legal"><a id="listiaPrivacyLink" href="/privacy.html">Privacy Notice</a><a id="listiaTermsLink" href="/terms.html">Terms &amp; Conditions</a></nav><span class="listia-powered">Powered by <a href="/cloudco">CloudCo</a></span></div>`;const right=document.createElement('div');right.className='listia-footer-right';if(domain)right.appendChild(domain);if(tag)right.appendChild(tag);footer.replaceChildren(main,right);return main}
  function apply(lang){styles();if(!ensure())return;const t=copy[normalize(lang||document.documentElement.dataset.listiaLanguage||document.documentElement.lang)]||copy.en;document.getElementById('listiaFooterRights').textContent=t.rights;document.getElementById('listiaPrivacyLink').textContent=t.privacy;document.getElementById('listiaTermsLink').textContent=t.terms}
  function load(src,key){if(document.querySelector(`script[data-${key}]`))return;const script=document.createElement('script');script.src=src;script.defer=true;script.setAttribute(`data-${key}`,'1');document.head.appendChild(script)}
  function init(){load('/global-locales.js?v=2','listia-commercial-global-locales');load('/japanese-locale.js?v=1','listia-commercial-japanese-locale');apply(window.ListiaI18n?.get?.()||document.documentElement.dataset.listiaLanguage||document.documentElement.lang);window.addEventListener('listia:languagechange',e=>apply(e.detail?.language))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
