(() => {
  const key='ja';
  const t={htmlLang:'ja-JP',dir:'ltr',label:'日本語',aliases:['ja','ja-jp'],title:'Listia — AI不動産プラットフォーム',description:'Listia を開くか、iPhone、Android、パソコンにインストールできます。',languageLabel:'言語を選択',heroEyebrow:'AI不動産',heroTitle:'<span class="accent">Listia</span> を開く<br>またはデバイスにインストール',heroLede:'AIで不動産業務を支えるプラットフォーム。iPhone、Android、パソコンで利用できます。',access:'Listia を開く',freeTag:'アプリを無料でダウンロード',desktop:'パソコン版をダウンロード',brandTitle:'AIで動く<span class="accent">不動産</span>プラットフォーム',brandLede:'時間を節約し、より多くの見込み客を獲得し、業務を自動化して<strong>より多くの成約</strong>へ。すべてをひとつに。',devicesEyebrow:'どの画面でも同じ Listia',devicesTitle:'ノートPC、タブレット、スマートフォンの Listia',devicesAlt:'ノートPC、タブレット、スマートフォン上の Listia',footerTagline:'AI不動産'};
  const norm=v=>{const c=String(v||'').trim().toLowerCase().replaceAll('_','-');return t.aliases.includes(c)||t.aliases.includes(c.split('-')[0])?key:null};
  const text=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v},html=(id,v)=>{const e=document.getElementById(id);if(e)e.innerHTML=v};
  const persist=()=>{try{localStorage.setItem('listia_language',key)}catch{}document.cookie='listia_lang=ja;path=/;max-age=31536000;SameSite=Lax'};
  function option(){const s=document.getElementById('languageSelect');if(s&&!s.querySelector('option[value="ja"]')){const o=document.createElement('option');o.value='ja';o.textContent=t.label;s.append(o);}}
  function hreflang(){if(document.head.querySelector('link[rel="alternate"][hreflang="ja"]'))return;const l=document.createElement('link');l.rel='alternate';l.hreflang='ja';l.href='https://listiaapp.com/?lang=ja';document.head.append(l);}
  function apply(persistChoice=false){if(persistChoice)persist();document.documentElement.lang=t.htmlLang;document.documentElement.dir=t.dir;document.documentElement.dataset.listiaLanguage=key;document.title=t.title;const d=document.querySelector('meta[name="description"]');if(d)d.content=t.description;const c=document.getElementById('canonicalUrl');if(c)c.href='https://listiaapp.com/?lang=ja';text('languageLabel',t.languageLabel);text('heroEyebrow',t.heroEyebrow);html('heroTitle',t.heroTitle);text('heroLede',t.heroLede);text('accederBtn',t.access);text('freeTag',t.freeTag);text('desktopBtnLabel',t.desktop);html('brandTitle',t.brandTitle);html('brandLede',t.brandLede);text('devicesEyebrow',t.devicesEyebrow);text('devicesTitle',t.devicesTitle);text('footerTagline',t.footerTagline);const shot=document.getElementById('devicesShot');if(shot)shot.alt=t.devicesAlt;const s=document.getElementById('languageSelect');if(s){s.value=key;s.setAttribute('aria-label',t.languageLabel)}const a=document.getElementById('accederBtn');if(a){try{const u=new URL(a.href,location.href);u.searchParams.set('lang','ja');a.href=u.toString()}catch{}}window.LISTIA_LANGUAGE=key;window.dispatchEvent(new CustomEvent('listia:languagechange',{detail:{language:key,htmlLanguage:t.htmlLang,direction:t.dir}}));return true;}
  function patch(){const api=window.ListiaI18n;if(!api||api.__listiaJapanesePatched)return false;const baseSet=api.set?.bind(api),baseApply=api.apply?.bind(api),baseGet=api.get?.bind(api);api.set=l=>norm(l)?apply(true):baseSet?.(l);api.apply=l=>norm(l)?apply(false):baseApply?.(l);api.get=()=>document.documentElement.dataset.listiaLanguage==='ja'?'ja':baseGet?.()||'en';api.supported=[...new Set([...(api.supported||[]),'ja'])];api.__listiaJapanesePatched=true;return true;}
  function init(){option();hreflang();patch();const s=document.getElementById('languageSelect');if(s&&!s.dataset.jaBound){s.dataset.jaBound='1';s.addEventListener('change',e=>{if(norm(e.target.value)){e.stopImmediatePropagation();apply(true)}},true)}let initial=null;try{initial=norm(new URLSearchParams(location.search).get('lang'));if(!initial){const m=document.cookie.match(/(?:^|;\s*)listia_lang=([^;]+)/);if(m)initial=norm(decodeURIComponent(m[1]));}if(!initial)initial=norm(localStorage.getItem('listia_language'));}catch{}if(!initial){for(const c of (navigator.languages?.length?navigator.languages:[navigator.language])){initial=norm(c);if(initial)break;}}if(initial)apply(false);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
