(()=>{'use strict';
const FEED='/marketplace/api/feed',PAGE=30;
let rows=[],total=0,offset=0,map=null,markers=[],detailMap=null,busy=false;
const $=id=>document.getElementById(id),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=(v,c='MXN')=>{if(v===null||v===undefined||v==='')return'';try{return new Intl.NumberFormat('es-MX',{style:'currency',currency:c||'MXN',maximumFractionDigits:0}).format(Number(v))}catch{return `${Number(v||0).toLocaleString()} ${c||''}`}};
function gallery(x){const out=[];const add=v=>{const s=String(v||'').trim();if(/^https:\/\//i.test(s)&&!out.includes(s))out.push(s)};add(x.cover_image_url);if(Array.isArray(x.gallery))x.gallery.forEach(v=>add(typeof v==='string'?v:v?.url||v?.src||v?.image_url));return out.slice(0,24)}
function initMap(){map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([20.75,-87.1],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function filters(){const n=id=>{const v=String($(id)?.value||'').trim();return v&&Number.isFinite(Number(v))?Number(v):null};return{p_limit:PAGE,p_offset:offset,p_q:String($('q')?.value||'').trim()||null,p_operation:$('op')?.value||null,p_property_type:String($('type')?.value||'').trim()||null,p_min_price:n('min'),p_max_price:n('max'),p_bedrooms:n('beds')}}
async function feed(){const r=await fetch(FEED,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(filters()),credentials:'same-origin',cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);return Array.isArray(d)?d:[]}
function clearMarkers(){markers.forEach(m=>m.remove());markers=[]}
function addMarker(x){const lat=Number(x.latitude),lng=Number(x.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!lat||!lng)return;const m=L.circleMarker([lat,lng],{radius:7,weight:2,color:'#fff',fillColor:'#7c2ce6',fillOpacity:.9}).addTo(map);m.bindPopup(`<div class="popupprice">${esc(money(x.price,x.currency))}</div><div>${esc(x.title||'Propiedad')}</div><div class="popupsmall">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div>`);m.on('click',()=>openDetail(x));markers.push(m)}
function card(x){const a=document.createElement('article');a.className='card';const imgs=gallery(x);const media=imgs[0]?`<img loading="lazy" decoding="async" draggable="false" referrerpolicy="no-referrer" src="${esc(imgs[0])}" alt="${esc(x.title||'Propiedad en LISTIA')}">`:'<span>Imagen no disponible</span>';a.innerHTML=`<div class="photo" role="button" tabindex="0">${media}</div><div class="body"><div class="price">${esc(money(x.price,x.currency))}</div><div class="title">${esc(x.title||'Propiedad')}</div><div class="loc">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div><div class="meta">${x.bedrooms!=null?`<span>${esc(x.bedrooms)} rec.</span>`:''}${x.bathrooms!=null?`<span>${esc(x.bathrooms)} baños</span>`:''}${x.area_m2?`<span>${esc(x.area_m2)} m²</span>`:''}</div><span class="badge">${x.operation_type==='rent'?'Renta':'Venta'}</span><div class="cardActions"><button class="btn detailBtn" type="button">Ver propiedad</button></div></div>`;const open=()=>openDetail(x);a.querySelector('.photo').onclick=open;a.querySelector('.photo').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};a.querySelector('.detailBtn').onclick=open;return a}
function render(){const list=$('list');list.replaceChildren();if(!rows.length){list.innerHTML='<div class="empty"><strong>No encontré coincidencias exactas.</strong><br><br>Prueba otra zona, cambia el rango o habla con LISTIA.</div>'}else rows.forEach(x=>list.append(card(x)));$('count').innerHTML=`<strong>${total.toLocaleString('es-MX')}</strong> propiedades encontradas`;const more=$('loadMore');more.hidden=!rows.length||rows.length>=total;more.disabled=busy;clearMarkers();rows.forEach(addMarker);if(markers.length){const group=L.featureGroup(markers);try{map.fitBounds(group.getBounds().pad(.12),{maxZoom:13})}catch{}}}
async function load(reset=true){if(busy)return;busy=true;const search=$('searchBtn'),more=$('loadMore');search.disabled=true;more.disabled=true;if(reset){offset=0;rows=[];$('list').innerHTML='<div class="loading">LISTIA está buscando propiedades…</div>';$('count').textContent='Buscando…'}try{const data=await feed();const known=new Set(rows.map(x=>String(x.id)));const fresh=data.filter(x=>!known.has(String(x.id)));rows=reset?fresh:[...rows,...fresh];total=data.length?Number(data[0].total_count||rows.length):(reset?0:total);offset=rows.length;render()}catch(e){console.error('LISTIA Marketplace',e);if(reset){$('list').innerHTML='<div class="empty">No pudimos cargar el inventario en este momento. Intenta nuevamente.</div>';$('count').textContent='Marketplace'}}finally{busy=false;search.disabled=false;more.disabled=!rows.length||rows.length>=total}}
function closeDetail(){if(detailMap){detailMap.remove();detailMap=null}$('detailOverlay').classList.remove('open');$('detailOverlay').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function openDetail(x){if(detailMap){detailMap.remove();detailMap=null}const content=$('detailContent'),imgs=gallery(x),stats=[];if(x.bedrooms!=null)stats.push(`${esc(x.bedrooms)} recámaras`);if(x.bathrooms!=null)stats.push(`${esc(x.bathrooms)} baños`);if(x.parking_spaces!=null)stats.push(`${esc(x.parking_spaces)} estacionamientos`);if(x.area_m2)stats.push(`${esc(x.area_m2)} m²`);const thumbs=imgs.length>1?`<div class="thumbRail">${imgs.map((u,i)=>`<button class="thumb${i===0?' active':''}" type="button" data-src="${esc(u)}"><img loading="lazy" decoding="async" draggable="false" referrerpolicy="no-referrer" src="${esc(u)}" alt=""></button>`).join('')}</div>`:'';const hero=imgs[0]?`<div class="detailGallery"><div class="detailHero"><img id="detailHeroImg" draggable="false" referrerpolicy="no-referrer" src="${esc(imgs[0])}" alt="${esc(x.title||'Propiedad')}"></div>${thumbs}</div>`:'';content.innerHTML=`${hero}<h2 id="detailTitle">${esc(x.title||'Propiedad')}</h2><div class="price">${esc(money(x.price,x.currency))}</div><div class="loc">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div>${stats.length?`<div class="detailStats">${stats.map(s=>`<span>${s}</span>`).join('')}</div>`:''}${x.description?`<p class="detailDesc">${esc(x.description)}</p>`:''}<div id="detailMapHost"></div><div class="detailBottom"><a class="btn primary" rel="nofollow" href="https://app.listiaapp.com/?marketplace=1&listing=${encodeURIComponent(x.id||'')}">Me interesa</a><button class="btn" id="detailCloseBottom" type="button">Cerrar</button></div>`;$('detailOverlay').classList.add('open');$('detailOverlay').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');content.querySelectorAll('.thumb').forEach(b=>b.onclick=()=>{const h=$('detailHeroImg');if(h)h.src=b.dataset.src||'';content.querySelectorAll('.thumb').forEach(q=>q.classList.toggle('active',q===b))});$('detailCloseBottom').onclick=closeDetail;const lat=Number(x.latitude),lng=Number(x.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng)&&lat&&lng){const host=$('detailMapHost');host.innerHTML='<div class="detailHero" id="detailMap" aria-label="Mapa de la propiedad"></div>';setTimeout(()=>{detailMap=L.map('detailMap',{zoomControl:true}).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(detailMap);L.circleMarker([lat,lng],{radius:8,color:'#fff',weight:2,fillColor:'#7c2ce6',fillOpacity:1}).addTo(detailMap)},40)}}
function setView(mode){const list=$('listColumn'),mw=$('mapWrap'),ws=$('workspace');$('bothBtn').classList.toggle('active',mode==='both');$('mapBtn').classList.toggle('active',mode==='map');$('listBtn').classList.toggle('active',mode==='list');if(mode==='map'){list.hidden=true;mw.hidden=false;ws.style.gridTemplateColumns='1fr'}else if(mode==='list'){list.hidden=false;mw.hidden=true;ws.style.gridTemplateColumns='1fr'}else{list.hidden=false;mw.hidden=false;ws.style.gridTemplateColumns='minmax(420px,1fr) minmax(420px,1.08fr)'}setTimeout(()=>map.invalidateSize(),50)}
function initial(){const q=document.body.dataset.marketQuery||'';if(q)$('q').value=q;initMap();$('searchBtn').onclick=()=>load(true);$('loadMore').onclick=()=>load(false);$('talkBtn').onclick=()=>{const u=new URL('https://app.listiaapp.com/');u.searchParams.set('marketplace','1');u.searchParams.set('voice','1');location.href=u};['q','type','beds','min','max'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter')load(true)}));$('op').onchange=()=>{};$('detailClose').onclick=closeDetail;$('detailOverlay').onclick=e=>{if(e.target===$('detailOverlay'))closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});$('bothBtn').onclick=()=>setView('both');$('mapBtn').onclick=()=>setView('map');$('listBtn').onclick=()=>setView('list');load(true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initial,{once:true});else initial();
})();