(()=>{'use strict';
const FEED='/marketplace/api/feed',PAGE=30;
let rows=[],total=0,offset=0,map=null,markers=[],detailMap=null,busy=false,currentView='both',recognition=null;
const $=id=>document.getElementById(id);
const mobile=()=>matchMedia('(max-width:650px)').matches;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=(v,c='MXN')=>{if(v===null||v===undefined||v==='')return'';try{return new Intl.NumberFormat('es-MX',{style:'currency',currency:c||'MXN',maximumFractionDigits:0}).format(Number(v))}catch{return `${Number(v||0).toLocaleString()} ${c||''}`}};
function gallery(x){const out=[];const add=v=>{const s=String(v||'').trim();if(/^https:\/\//i.test(s)&&!out.includes(s))out.push(s)};add(x.cover_image_url);if(Array.isArray(x.gallery))x.gallery.forEach(v=>add(typeof v==='string'?v:v?.url||v?.src||v?.image_url));return out.slice(0,40)}
function initMap(){map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([20.75,-87.1],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);map.on('popupopen',e=>{const b=e.popup.getElement()?.querySelector('[data-listing]');if(!b)return;const x=rows.find(r=>String(r.id)===String(b.dataset.listing));if(x)b.onclick=()=>openDetail(x)})}
function filters(){const n=id=>{const v=String($(id)?.value||'').trim();return v&&Number.isFinite(Number(v))?Number(v):null};return{p_limit:PAGE,p_offset:offset,p_q:String($('q')?.value||'').trim()||null,p_operation:$('op')?.value||null,p_property_type:String($('type')?.value||'').trim()||null,p_min_price:n('min'),p_max_price:n('max'),p_bedrooms:n('beds')}}
async function feed(){const r=await fetch(FEED,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(filters()),credentials:'same-origin',cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);return Array.isArray(d)?d:[]}
function clearMarkers(){markers.forEach(m=>m.remove());markers=[]}
function addMarker(x){const lat=Number(x.latitude),lng=Number(x.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!lat||!lng)return;const m=L.circleMarker([lat,lng],{radius:7,weight:2,color:'#fff',fillColor:'#7c2ce6',fillOpacity:.92}).addTo(map);m.bindPopup(`<div class="popupprice">${esc(money(x.price,x.currency))}</div><div>${esc(x.title||'Propiedad')}</div><div class="popupsmall">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div><button class="btn primary" style="margin-top:8px;width:100%;min-height:38px;padding:7px 10px;font-size:12px" data-listing="${esc(x.id)}">Me interesa</button>`);markers.push(m)}
function card(x){const a=document.createElement('article');a.className='card';const imgs=gallery(x);const media=imgs[0]?`<img loading="lazy" decoding="async" draggable="false" referrerpolicy="no-referrer" src="${esc(imgs[0])}" alt="${esc(x.title||'Propiedad en LISTIA')}">${imgs.length?`<span class="photoCount">${imgs.length} fotos</span>`:''}`:'<span style="font-size:12px;color:#aaa3b1">Imagen no disponible</span>';a.innerHTML=`<div class="photo">${media}</div><div class="body"><div class="price">${esc(money(x.price,x.currency))}</div><div class="title">${esc(x.title||'Propiedad')}</div><div class="loc">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div><div class="meta">${x.bedrooms!=null?`<span>${esc(x.bedrooms)} rec.</span>`:''}${x.bathrooms!=null?`<span>${esc(x.bathrooms)} baños</span>`:''}${x.area_m2?`<span>${esc(x.area_m2)} m²</span>`:''}</div><span class="badge">${x.operation_type==='rent'?'Renta':'Venta'}</span><div class="cardActions"><button class="btn primary interestBtn" type="button">Me interesa</button></div></div>`;a.querySelector('.interestBtn').onclick=()=>openDetail(x);return a}
function median(vals){const a=vals.filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function renderPulse(){const inv=$('pulseInventory'),med=$('pulseMedian'),sale=$('pulseSale'),top=$('pulseTop'),bars=$('pulseBars');if(!inv)return;inv.textContent=total?total.toLocaleString('es-MX'):'0';const currency=rows.find(x=>x.price!=null)?.currency||'MXN';const md=median(rows.map(x=>Number(x.price)));med.textContent=md!=null?money(md,currency):'—';const saleCount=rows.filter(x=>x.operation_type!=='rent').length;sale.textContent=rows.length?`${Math.round(saleCount/rows.length*100)}%`:'—';const counts={};for(const x of rows){const k=String(x.city||x.location_text||'Sin zona').trim()||'Sin zona';counts[k]=(counts[k]||0)+1}const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);top.textContent=ranked[0]?.[0]||'—';bars.replaceChildren();const max=ranked[0]?.[1]||1;for(const [name,value] of ranked){const row=document.createElement('div');row.className='pulseBar';row.innerHTML=`<span class="pulseBarName">${esc(name)}</span><span class="pulseTrack"><span class="pulseFill" style="width:${Math.max(5,Math.round(value/max*100))}%"></span></span><strong class="pulseBarValue">${value}</strong>`;bars.append(row)}if(!ranked.length)bars.innerHTML='<span style="font-size:12px;color:#aaa3b1">Sin datos suficientes en esta búsqueda.</span>'}
function render(){const list=$('list');list.replaceChildren();if(!rows.length){list.innerHTML='<div class="empty"><strong>No encontré coincidencias exactas.</strong><br><br>Prueba otra zona, cambia el rango o habla con LISTIA.</div>'}else rows.forEach(x=>list.append(card(x)));$('count').innerHTML=`<strong>${total.toLocaleString('es-MX')}</strong> propiedades`;const more=$('loadMore');more.hidden=!rows.length||rows.length>=total;more.disabled=busy;clearMarkers();rows.forEach(addMarker);renderPulse();if(markers.length){const group=L.featureGroup(markers);try{map.fitBounds(group.getBounds().pad(.12),{maxZoom:13})}catch{}}setTimeout(()=>map?.invalidateSize(),60)}
async function load(reset=true){if(busy)return;busy=true;const search=$('searchBtn'),mobileSearch=$('mobileSearchBtn'),more=$('loadMore');if(search)search.disabled=true;if(mobileSearch)mobileSearch.disabled=true;more.disabled=true;if(reset){offset=0;rows=[];$('list').innerHTML='<div class="loading">LISTIA está buscando propiedades…</div>';$('count').textContent='Buscando…'}try{const data=await feed();const known=new Set(rows.map(x=>String(x.id)));const fresh=data.filter(x=>!known.has(String(x.id)));rows=reset?fresh:[...rows,...fresh];total=data.length?Number(data[0].total_count||rows.length):(reset?0:total);offset=rows.length;render()}catch(e){console.error('LISTIA Marketplace',e);if(reset){$('list').innerHTML='<div class="empty">No pudimos cargar el inventario en este momento. Intenta nuevamente.</div>';$('count').textContent='Marketplace'}}finally{busy=false;if(search)search.disabled=false;if(mobileSearch)mobileSearch.disabled=false;more.disabled=!rows.length||rows.length>=total}}
function closeDetail(){if(detailMap){detailMap.remove();detailMap=null}$('detailOverlay').classList.remove('open');$('detailOverlay').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function openDetail(x){if(detailMap){detailMap.remove();detailMap=null}const content=$('detailContent'),imgs=gallery(x),stats=[];if(x.bedrooms!=null)stats.push(`${esc(x.bedrooms)} recámaras`);if(x.bathrooms!=null)stats.push(`${esc(x.bathrooms)} baños`);if(x.parking_spaces!=null)stats.push(`${esc(x.parking_spaces)} estacionamientos`);if(x.area_m2)stats.push(`${esc(x.area_m2)} m²`);const thumbs=imgs.length>1?`<div class="thumbRail">${imgs.map((u,i)=>`<button class="thumb${i===0?' active':''}" type="button" data-src="${esc(u)}"><img loading="lazy" decoding="async" draggable="false" referrerpolicy="no-referrer" src="${esc(u)}" alt=""></button>`).join('')}</div>`:'';const hero=imgs[0]?`<div class="detailGallery"><div class="detailHero"><img id="detailHeroImg" draggable="false" referrerpolicy="no-referrer" src="${esc(imgs[0])}" alt="${esc(x.title||'Propiedad')}"></div>${thumbs}</div>`:'<div class="detailHero"><span style="font-size:12px;color:#aaa3b1">Imágenes en preparación</span></div>';content.innerHTML=`${hero}<div><h2 id="detailTitle">${esc(x.title||'Propiedad')}</h2><div class="price">${esc(money(x.price,x.currency))}</div><div class="loc">${esc(x.location_text||[x.city,x.state_region].filter(Boolean).join(', '))}</div>${stats.length?`<div class="detailStats">${stats.map(s=>`<span>${s}</span>`).join('')}</div>`:''}${x.description?`<p class="detailDesc">${esc(x.description)}</p>`:''}<div id="detailMapHost"></div><div class="detailBottom"><a class="btn primary" rel="nofollow" href="https://app.listiaapp.com/?marketplace=1&listing=${encodeURIComponent(x.id||'')}&interest=1">Continuar con mi interés</a><button class="btn" id="detailCloseBottom" type="button">Cerrar</button></div></div>`;$('detailOverlay').classList.add('open');$('detailOverlay').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');content.querySelectorAll('.thumb').forEach(b=>b.onclick=()=>{const h=$('detailHeroImg');if(h)h.src=b.dataset.src||'';content.querySelectorAll('.thumb').forEach(q=>q.classList.toggle('active',q===b))});$('detailCloseBottom').onclick=closeDetail;const lat=Number(x.latitude),lng=Number(x.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng)&&lat&&lng&&!mobile()){const host=$('detailMapHost');host.innerHTML='<div class="detailHero" id="detailMap" aria-label="Mapa de la propiedad"></div>';setTimeout(()=>{detailMap=L.map('detailMap',{zoomControl:true}).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(detailMap);L.circleMarker([lat,lng],{radius:8,color:'#fff',weight:2,fillColor:'#7c2ce6',fillOpacity:1}).addTo(detailMap)},40)}}
function setView(mode){currentView=mode;const list=$('listColumn'),mw=$('mapWrap'),pulse=$('pulseWrap'),ws=$('workspace');['bothBtn','mapBtn','listBtn','pulseBtn'].forEach(id=>$(id)?.classList.remove('active'));const active={both:'bothBtn',map:'mapBtn',list:'listBtn',pulse:'pulseBtn'}[mode];$(active)?.classList.add('active');list.hidden=!(mode==='list'||mode==='both');mw.hidden=!(mode==='map'||mode==='both');pulse.hidden=mode!=='pulse';if(mode==='both'){ws.style.gridTemplateColumns='minmax(420px,1fr) minmax(420px,1.08fr)'}else ws.style.gridTemplateColumns='1fr';setTimeout(()=>map?.invalidateSize(),60)}
function syncMobileQuery(){const mq=$('mobileQ');if(mq&&$('q'))$('q').value=mq.value.trim()}
function toggleFilters(){const p=$('filtersPanel'),b=$('filterToggle');const open=!p.classList.contains('mobile-open');p.classList.toggle('mobile-open',open);b.setAttribute('aria-expanded',String(open))}
function closeFilters(){const p=$('filtersPanel'),b=$('filterToggle');p?.classList.remove('mobile-open');b?.setAttribute('aria-expanded','false')}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){const u=new URL('https://app.listiaapp.com/');u.searchParams.set('marketplace','1');u.searchParams.set('voice','1');location.href=u;return}if(recognition){try{recognition.stop()}catch{}recognition=null}recognition=new SR();recognition.lang='es-MX';recognition.interimResults=false;recognition.maxAlternatives=1;const btn=$('talkBtn'),hint=$('voiceHint');btn.textContent='Escuchando…';hint.textContent='Habla con naturalidad. LISTIA está escuchando.';recognition.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript?.trim()||'';if(text){$('q').value=text;if($('mobileQ'))$('mobileQ').value=text;hint.textContent=`“${text}”`;load(true);if(mobile())setView('map')}};recognition.onerror=()=>{hint.textContent='No pude escucharte. Intenta otra vez.'};recognition.onend=()=>{btn.textContent='Hablar con LISTIA';recognition=null};recognition.start()}
function initial(){const q=document.body.dataset.marketQuery||'';if(q){$('q').value=q;if($('mobileQ'))$('mobileQ').value=q}const path=location.pathname.replace(/\/+$/,'');if(path.endsWith('/venta'))$('op').value='sale';else if(path.endsWith('/renta'))$('op').value='rent';initMap();$('searchBtn').onclick=()=>load(true);$('mobileSearchBtn').onclick=()=>{syncMobileQuery();closeFilters();load(true)};$('mobileQ').addEventListener('keydown',e=>{if(e.key==='Enter'){syncMobileQuery();closeFilters();load(true)}});$('filterToggle').onclick=toggleFilters;$('loadMore').onclick=()=>load(false);$('talkBtn').onclick=startVoice;['q','type','beds','min','max'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter'){closeFilters();load(true)}}));$('op').onchange=()=>{};$('detailClose').onclick=closeDetail;$('detailOverlay').onclick=e=>{if(e.target===$('detailOverlay'))closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeFilters();closeDetail()}});$('bothBtn').onclick=()=>setView('both');$('mapBtn').onclick=()=>setView('map');$('listBtn').onclick=()=>setView('list');$('pulseBtn').onclick=()=>setView('pulse');window.addEventListener('resize',()=>{if(mobile()&&currentView==='both')setView('map');else setTimeout(()=>map?.invalidateSize(),80)});setView(mobile()?'map':'both');load(true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initial,{once:true});else initial();
})();