import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'
import postgres from 'https://deno.land/x/postgresjs@v3.4.7/mod.js'

const URL=Deno.env.get('SUPABASE_URL')!
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ANON=Deno.env.get('SUPABASE_ANON_KEY')!
const DB=Deno.env.get('SUPABASE_DB_URL')!
const GOOGLE_CLIENT_ID=Deno.env.get('GOOGLE_OAUTH_CLIENT_ID')
const GOOGLE_CLIENT_SECRET=Deno.env.get('GOOGLE_OAUTH_CLIENT_SECRET')
const sql=postgres(DB,{prepare:false,max:2})
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})
const allowedOrigins=new Set(['https://app.listiaapp.com','https://listia-pwa.pages.dev'])
const platforms=['meta','google','tiktok','linkedin']
const blockedVerification=new Set(['bot','suspicious','duplicate','fake','invalid','blocked','junk','spam'])

type Result={ok:boolean,httpStatus:number,externalId?:string|null,retryable?:boolean,error?:string|null,meta?:Record<string,unknown>}

function cors(req:Request){const o=req.headers.get('origin')||'';return {'access-control-allow-origin':allowedOrigins.has(o)?o:'https://app.listiaapp.com','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, apikey, content-type, x-listia-conversion-dispatch-key','vary':'Origin'}}
function out(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function clamp(n:number,a:number,b:number){return Math.min(b,Math.max(a,n))}
function text(v:unknown){return String(v??'').trim()}
function lower(v:unknown){return text(v).toLowerCase()}
function safeError(v:unknown){return text(v).slice(0,500)||'unknown_error'}
function retryDelay(attempt:number){return [60,300,900,3600,21600][Math.min(Math.max(attempt-1,0),4)]}
function asNum(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}
function normalizeEmail(v:unknown){return lower(v)}
function normalizePhone(v:unknown){const raw=text(v);if(!raw)return'';const plus=raw.startsWith('+');const digits=raw.replace(/\D/g,'');return digits?(plus?'+':'')+digits:''}
async function sha256(v:string){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hashedPII(lead:any,allow:boolean){if(!allow)return{email:null,phone:null};const e=normalizeEmail(lead?.email),p=normalizePhone(lead?.whatsapp);return{email:e?await sha256(e):null,phone:p?await sha256(p):null}}
function consentGranted(lead:any){const a=lead?.attribution||{},s=lead?.source_detail||{},c=a.consent||s.consent||{};const v=lower(c.ad_user_data??c.adUserData??c.marketing??a.marketing_consent??s.marketing_consent);return ['granted','true','yes','1','accepted'].includes(v)}
function clickIds(lead:any,touch:any){return {...(lead?.attribution?.click_ids||{}),...(lead?.attribution||{}),...(touch?.click_ids||{})}}
function valueAndCurrency(signal:any){const p=signal?.payload||{};return{value:asNum(p.conversion_value??p.value??p.revenue),currency:text(p.currency||'USD').toUpperCase().slice(0,3)||'USD'}}

async function internalAuth(req:Request){const supplied=req.headers.get('x-listia-conversion-dispatch-key')||'';if(!supplied)return false;const [row]=await sql`select decrypted_secret from vault.decrypted_secrets where name='listia_conversion_dispatch_secret' limit 1`;return Boolean(row?.decrypted_secret)&&supplied===String(row.decrypted_secret)}
async function userAuth(req:Request){const auth=req.headers.get('authorization')||'';if(!auth)return null;const client=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user}}=await client.auth.getUser();return user||null}
async function refreshGoogleToken(connectionId:string,row:any){if(!row?.refresh_token||!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET)return null;const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:GOOGLE_CLIENT_ID,client_secret:GOOGLE_CLIENT_SECRET,refresh_token:String(row.refresh_token),grant_type:'refresh_token'})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.access_token)return null;const exp=data.expires_in?new Date(Date.now()+Number(data.expires_in)*1000).toISOString():null;if(row.access_token_secret_id)await sql`select vault.update_secret(${row.access_token_secret_id}::uuid,${String(data.access_token)},null,null,null::uuid)`;await sql`update private.integration_token_refs set token_expires_at=${exp}::timestamptz,updated_at=now() where connection_id=${connectionId}::uuid`;return String(data.access_token)}
async function loadToken(connection:any){const [row]=await sql`select r.access_token_secret_id,r.refresh_token_secret_id,r.token_expires_at,a.decrypted_secret as access_token,rr.decrypted_secret as refresh_token from private.integration_token_refs r left join vault.decrypted_secrets a on a.id=r.access_token_secret_id left join vault.decrypted_secrets rr on rr.id=r.refresh_token_secret_id where r.connection_id=${connection.id}::uuid limit 1`;if(!row?.access_token)return null;const expires=row.token_expires_at?new Date(row.token_expires_at).getTime():null;if(expires&&expires<Date.now()+60000){if(connection.provider==='google'){const refreshed=await refreshGoogleToken(connection.id,row);if(refreshed)return refreshed}return null}return String(row.access_token)}
async function leadContext(signal:any){if(!signal.lead_id)return{lead:null,touch:null};const [lead]=await sql`select id,name,email,whatsapp,verification_status,quality_score,lead_score,source,source_detail,attribution from public.leads where id=${signal.lead_id}::uuid and organization_id=${signal.organization_id}::uuid limit 1`;if(!lead)return{lead:null,touch:null};const [touch]=await sql`select source,medium,campaign,content,term,click_ids,landing_url,referrer,occurred_at from public.attribution_touchpoints where organization_id=${signal.organization_id}::uuid and lead_id=${signal.lead_id}::uuid order by occurred_at desc limit 1`;return{lead,touch:touch||null}}
function configuration(connection:any,signal:any){const p=lower(connection.provider),m=connection.metadata||{},scopes=(connection.granted_scopes||[]).map((x:string)=>lower(x));if(!platforms.includes(p))return{ready:false,reason:'unsupported_provider'};if(p==='meta'){const id=text(m.dataset_id||m.pixel_id);return id?{ready:true,asset:id}:{ready:false,reason:'meta_dataset_required'}}if(p==='google'){const scope=scopes.some((s:string)=>s.includes('datamanager'));const customer=text(m.google_ads_customer_id||m.customer_id);const actions=m.conversion_actions||{};const action=text(actions[signal.signal_type]||m.conversion_action_id);if(!scope)return{ready:false,reason:'google_datamanager_scope_required'};if(!customer)return{ready:false,reason:'google_ads_customer_required'};if(!action)return{ready:false,reason:'google_conversion_action_required'};return{ready:true,customer,action}}if(p==='tiktok'){const source=text(m.event_source_id||m.pixel_id);return source?{ready:true,source}:{ready:false,reason:'tiktok_event_source_required'}}if(p==='linkedin'){const ids=m.conversion_ids||{};const id=text(ids[signal.signal_type]||m.conversion_id);return id?{ready:true,conversion:id}:{ready:false,reason:'linkedin_conversion_required'}}return{ready:false,reason:'unsupported_provider'}}
async function upsertDelivery(signal:any,connection:any){const [d]=await sql`insert into private.conversion_signal_deliveries(signal_id,organization_id,connection_id,platform,status,external_event_id) values(${signal.id}::uuid,${signal.organization_id}::uuid,${connection.id}::uuid,${connection.provider},'queued',${`listia:${signal.id}:${connection.provider}`}) on conflict(signal_id,platform,connection_id) do update set updated_at=now() returning *`;return d}
async function startDelivery(id:string){const [d]=await sql`update private.conversion_signal_deliveries set status='processing',attempts=attempts+1,updated_at=now() where id=${id}::uuid returning *`;return d}
async function finishDelivery(d:any,r:Result){const attempt=Number(d.attempts||1);if(r.ok){await sql`update private.conversion_signal_deliveries set status='sent',last_http_status=${r.httpStatus},last_error=null,response_metadata=${JSON.stringify(r.meta||{})}::jsonb,external_event_id=coalesce(${r.externalId||null},external_event_id),delivered_at=now(),next_attempt_at=null,updated_at=now() where id=${d.id}::uuid`;return'sent'}const retry=Boolean(r.retryable)&&attempt<5;const next=retry?new Date(Date.now()+retryDelay(attempt)*1000).toISOString():null;await sql`update private.conversion_signal_deliveries set status=${retry?'failed':'suppressed'},last_http_status=${r.httpStatus||null},last_error=${safeError(r.error)},response_metadata=${JSON.stringify(r.meta||{})}::jsonb,next_attempt_at=${next}::timestamptz,updated_at=now() where id=${d.id}::uuid`;return retry?'failed':'suppressed'}

async function sendMeta(signal:any,connection:any,token:string,lead:any,touch:any,allowPII:boolean):Promise<Result>{const m=connection.metadata||{},dataset=text(m.dataset_id||m.pixel_id),api=text(m.api_version||Deno.env.get('META_GRAPH_API_VERSION')||'v23.0'),ids=clickIds(lead,touch),pii=await hashedPII(lead,allowPII),user:any={};if(pii.email)user.em=[pii.email];if(pii.phone)user.ph=[pii.phone];if(ids.fbc)user.fbc=text(ids.fbc);if(ids.fbp)user.fbp=text(ids.fbp);if(lead?.id)user.external_id=[await sha256(String(lead.id))];const map:any={qualified_lead:'QualifiedLead',appointment:'Schedule',conversion:'Purchase'},vc=valueAndCurrency(signal);const event:any={event_name:(m.event_map||{})[signal.signal_type]||map[signal.signal_type],event_time:Math.floor(new Date(signal.event_time).getTime()/1000),event_id:`listia:${signal.id}`,action_source:'system_generated',user_data:user,custom_data:{currency:vc.currency,listia_signal_type:signal.signal_type}};if(vc.value!==null)event.custom_data.value=vc.value;if(touch?.landing_url)event.event_source_url=touch.landing_url;const body:any={data:[event]};if(m.test_event_code)body.test_event_code=m.test_event_code;const res=await fetch(`https://graph.facebook.com/${api}/${encodeURIComponent(dataset)}/events`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));const ok=res.ok&&Number(data.events_received||0)>=1;return{ok,httpStatus:res.status,retryable:res.status===429||res.status>=500,error:ok?null:(data?.error?.message||`meta_http_${res.status}`),meta:{events_received:data.events_received??null,trace_id:data.fbtrace_id??null}}}
async function sendGoogle(signal:any,connection:any,token:string,lead:any,touch:any,allowPII:boolean):Promise<Result>{const m=connection.metadata||{},customer=text(m.google_ads_customer_id||m.customer_id),actions=m.conversion_actions||{},action=text(actions[signal.signal_type]||m.conversion_action_id),ids=clickIds(lead,touch),pii=await hashedPII(lead,allowPII),ad:any={};for(const k of ['gclid','gbraid','wbraid'])if(ids[k])ad[k]=text(ids[k]);const event:any={eventTimestamp:new Date(signal.event_time).toISOString(),transactionId:`listia-${signal.id}`,eventSource:text(m.event_source||'WEB').toUpperCase()};if(Object.keys(ad).length)event.adIdentifiers=ad;const ui:any[]=[];if(pii.email)ui.push({emailAddress:pii.email});if(pii.phone)ui.push({phoneNumber:pii.phone});if(ui.length)event.userData={userIdentifiers:ui};const vc=valueAndCurrency(signal);if(vc.value!==null){event.conversionValue=vc.value;event.currency=vc.currency}if(!Object.keys(ad).length&&!ui.length)return{ok:false,httpStatus:422,retryable:false,error:'google_match_identifier_required'};const destination:any={reference:'listia_google_ads',operatingAccount:{accountType:'GOOGLE_ADS',accountId:customer},productDestinationId:action};if(m.login_customer_id)destination.loginAccount={accountType:'GOOGLE_ADS',accountId:text(m.login_customer_id)};const body:any={destinations:[destination],events:[{...event,destinationReferences:['listia_google_ads']}],validateOnly:Boolean(m.validate_only)};if(ui.length)body.encoding='HEX';const res=await fetch('https://datamanager.googleapis.com/v1/events:ingest',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));const ok=res.ok&&Boolean(data.requestId||m.validate_only);return{ok,httpStatus:res.status,externalId:data.requestId||null,retryable:res.status===429||res.status>=500,error:ok?null:(data?.error?.message||`google_http_${res.status}`),meta:{request_id:data.requestId??null,validate_only:Boolean(m.validate_only),warning_count:Array.isArray(data.fieldWarnings)?data.fieldWarnings.length:0}}}
async function sendTikTok(signal:any,connection:any,token:string,lead:any,touch:any,allowPII:boolean):Promise<Result>{const m=connection.metadata||{},source=text(m.event_source_id||m.pixel_id),ids=clickIds(lead,touch),pii=await hashedPII(lead,allowPII),user:any={};if(pii.email)user.email=[pii.email];if(pii.phone)user.phone=[pii.phone];if(ids.ttp)user.ttp=text(ids.ttp);if(ids.ttclid)user.ttclid=text(ids.ttclid);const sd=lead?.source_detail||{};if(m.allow_device_context&&sd.ip)user.ip=text(sd.ip);if(m.allow_device_context&&sd.user_agent)user.user_agent=text(sd.user_agent);const map:any={qualified_lead:'SubmitForm',appointment:'Schedule',conversion:'Purchase'},vc=valueAndCurrency(signal);const ev:any={event:(m.event_map||{})[signal.signal_type]||map[signal.signal_type],event_time:Math.floor(new Date(signal.event_time).getTime()/1000),event_id:`listia:${signal.id}`,user,properties:{currency:vc.currency,listia_signal_type:signal.signal_type}};if(vc.value!==null)ev.properties.value=vc.value;if(touch?.landing_url)ev.page={url:touch.landing_url};const body:any={event_source:'web',event_source_id:source,data:[ev]};if(m.test_event_code)body.test_event_code=m.test_event_code;const res=await fetch(text(m.events_endpoint||'https://business-api.tiktok.com/open_api/v1.3/event/track/'),{method:'POST',headers:{'Access-Token':token,'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));const code=Number(data.code??0),ok=res.ok&&code===0;return{ok,httpStatus:res.status,retryable:res.status===429||res.status>=500,error:ok?null:(data.message||`tiktok_http_${res.status}`),meta:{code:data.code??null,request_id:data.request_id??null}}}
async function sendLinkedIn(signal:any,connection:any,token:string,lead:any,touch:any,allowPII:boolean):Promise<Result>{const m=connection.metadata||{},ids=m.conversion_ids||{},conversion=text(ids[signal.signal_type]||m.conversion_id),pii=await hashedPII(lead,allowPII),click=clickIds(lead,touch),userIds:any[]=[];if(pii.email)userIds.push({idType:'SHA256_EMAIL',idValue:pii.email});if(click.li_fat_id)userIds.push({idType:'LINKEDIN_FIRST_PARTY_ADS_TRACKING_UUID',idValue:text(click.li_fat_id)});const user:any={userIds};if(lead?.id)user.externalIds=[String(lead.id)];const vc=valueAndCurrency(signal),body:any={conversion:`urn:lla:llaPartnerConversion:${conversion}`,conversionHappenedAt:new Date(signal.event_time).getTime(),user,eventId:`listia:${signal.id}`};if(vc.value!==null)body.conversionValue={currencyCode:vc.currency,amount:String(vc.value)};const version=text(m.linkedin_version||Deno.env.get('LINKEDIN_API_VERSION')||'202608');const res=await fetch('https://api.linkedin.com/rest/conversionEvents',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','Linkedin-Version':version,'X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));const ok=res.ok;return{ok,httpStatus:res.status,externalId:res.headers.get('x-restli-id'),retryable:res.status===429||res.status>=500,error:ok?null:(data?.message||data?.error?.message||`linkedin_http_${res.status}`),meta:{restli_id:res.headers.get('x-restli-id'),linkedin_version:version}}}
async function dispatchOne(signal:any,connection:any,lead:any,touch:any){const conf:any=configuration(connection,signal);if(!conf.ready)return{state:'not_ready',reason:conf.reason};const requireConsent=connection.metadata?.require_marketing_consent!==false;const granted=consentGranted(lead);if(requireConsent&&!granted){const d=await upsertDelivery(signal,connection);if(d.status!=='sent')await sql`update private.conversion_signal_deliveries set status='suppressed',last_error='marketing_consent_required',updated_at=now() where id=${d.id}::uuid`;return{state:'suppressed',reason:'marketing_consent_required'}}const minQ=asNum(connection.metadata?.min_quality_score),q=asNum(signal.quality_score??lead?.quality_score);if(blockedVerification.has(lower(lead?.verification_status))||(minQ!==null&&q!==null&&q<minQ)){const d=await upsertDelivery(signal,connection);if(d.status!=='sent')await sql`update private.conversion_signal_deliveries set status='suppressed',last_error='lead_quality_gate',updated_at=now() where id=${d.id}::uuid`;return{state:'suppressed',reason:'lead_quality_gate'}}const token=await loadToken(connection);if(!token){await admin.from('integration_connections').update({status:'needs_reauth',last_error:'conversion_access_token_unavailable'}).eq('id',connection.id);return{state:'not_ready',reason:'conversion_access_token_unavailable'}}let d=await upsertDelivery(signal,connection);if(d.status==='sent'||d.status==='suppressed')return{state:d.status};if(d.status==='failed'&&d.next_attempt_at&&new Date(d.next_attempt_at).getTime()>Date.now())return{state:'failed_backoff'};if(Number(d.attempts||0)>=5){await sql`update private.conversion_signal_deliveries set status='suppressed',last_error='retry_exhausted',updated_at=now() where id=${d.id}::uuid`;return{state:'suppressed',reason:'retry_exhausted'}}d=await startDelivery(d.id);let r:Result;try{if(connection.provider==='meta')r=await sendMeta(signal,connection,token,lead,touch,granted||!requireConsent);else if(connection.provider==='google')r=await sendGoogle(signal,connection,token,lead,touch,granted||!requireConsent);else if(connection.provider==='tiktok')r=await sendTikTok(signal,connection,token,lead,touch,granted||!requireConsent);else r=await sendLinkedIn(signal,connection,token,lead,touch,granted||!requireConsent)}catch(e){r={ok:false,httpStatus:0,retryable:true,error:safeError(e)}}const state=await finishDelivery(d,r);return{state,reason:r.error||null}}

async function claimSignals(org:string|null,limit:number){if(org)return await sql`with picked as (select id from public.conversion_signals where organization_id=${org}::uuid and (delivery_status in ('pending','failed','partial') or (delivery_status='processing' and updated_at<now()-interval '10 minutes')) order by created_at limit ${limit} for update skip locked) update public.conversion_signals s set delivery_status='processing',attempts=s.attempts+1,updated_at=now() from picked where s.id=picked.id returning s.*`;return await sql`with picked as (select id from public.conversion_signals where delivery_status in ('pending','failed','partial') or (delivery_status='processing' and updated_at<now()-interval '10 minutes') order by created_at limit ${limit} for update skip locked) update public.conversion_signals s set delivery_status='processing',attempts=s.attempts+1,updated_at=now() from picked where s.id=picked.id returning s.*`}
async function processSignal(signal:any){const {lead,touch}=await leadContext(signal);const conns=await sql`select id,organization_id,provider,status,granted_scopes,metadata from public.integration_connections where organization_id=${signal.organization_id}::uuid and status='connected' and provider=any(${signal.platforms}::text[]) order by provider`;const outcomes:any[]=[];let configured=0;for(const c of conns){const conf:any=configuration(c,signal);if(!conf.ready){outcomes.push({platform:c.provider,state:'not_ready',reason:conf.reason});continue}configured++;const o:any=await dispatchOne(signal,c,lead,touch);outcomes.push({platform:c.provider,...o})}if(configured===0){await sql`update public.conversion_signals set delivery_status='waiting',last_error='waiting_for_ad_connection',updated_at=now() where id=${signal.id}::uuid`;return{status:'waiting',outcomes}}const sent=outcomes.filter(x=>x.state==='sent').length,supp=outcomes.filter(x=>x.state==='suppressed').length,failed=outcomes.filter(x=>['failed','failed_backoff'].includes(x.state)).length;if(sent===configured){await sql`update public.conversion_signals set delivery_status='sent',last_error=null,delivered_at=now(),updated_at=now() where id=${signal.id}::uuid`;return{status:'sent',outcomes}}if(supp===configured){await sql`update public.conversion_signals set delivery_status='suppressed',last_error='all_configured_deliveries_suppressed',updated_at=now() where id=${signal.id}::uuid`;return{status:'suppressed',outcomes}}if(sent>0){await sql`update public.conversion_signals set delivery_status='partial',last_error=${`sent_${sent}_of_${configured}`},updated_at=now() where id=${signal.id}::uuid`;return{status:'partial',outcomes}}if(failed>0){await sql`update public.conversion_signals set delivery_status='failed',last_error='configured_delivery_failed',updated_at=now() where id=${signal.id}::uuid`;return{status:'failed',outcomes}}await sql`update public.conversion_signals set delivery_status='waiting',last_error='configured_connection_not_dispatchable',updated_at=now() where id=${signal.id}::uuid`;return{status:'waiting',outcomes}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,{error:'method_not_allowed'},405);try{const origin=req.headers.get('origin')||'';if(origin&&!allowedOrigins.has(origin))return out(req,{error:'origin_not_allowed'},403);const internal=await internalAuth(req);const user=internal?null:await userAuth(req);if(!internal&&!user)return out(req,{error:'unauthorized'},401);const body=await req.json().catch(()=>({})) as any;const limit=clamp(Number(body.limit||20),1,50);let org=body.organization_id?String(body.organization_id):null;if(!internal){if(!org)return out(req,{error:'organization_required'},400);const {data:member}=await admin.from('organization_members').select('role,status').eq('organization_id',org).eq('user_id',user!.id).eq('status','active').maybeSingle();if(!member||!['owner','admin'].includes(String(member.role)))return out(req,{error:'forbidden'},403)}const signals=await claimSignals(org,limit);const summary:any={processed:0,sent:0,partial:0,failed:0,suppressed:0,waiting:0};for(const s of signals){const r:any=await processSignal(s);summary.processed++;summary[r.status]=(summary[r.status]||0)+1}return out(req,{ok:true,...summary})}catch(e){console.error('conversion-signal-dispatch',e);return out(req,{error:'internal_error'},500)}})
