import { createClient } from 'jsr:@supabase/supabase-js@2';

const EXPECTED_HASH='e28ba70cf330106ef5328b7a02670f30eb14efff382c196d7013b5a8024c7c0f';
const UA='Mozilla/5.0 (compatible; LISTIA-MediaEnricher/4.0; +https://listiaapp.com)';
const STOP=new Set(['the','and','for','with','sale','venta','renta','property','properties','real','estate','mexico','casa','house','home','homes','departamento','apartment','condo','terreno','land','local','oficina','residencial','residential','de','del','la','las','los','en','con','para','una','uno','un']);
const sitemapCache=new Map<string,string[]>();

function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(v:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
function decode(s:string){return String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ')}
function strip(s:string){return decode(String(s||'').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim()}
function abs(raw:string,base:string){try{const v=decode(raw).trim();if(!v||/^(?:data|blob):/i.test(v))return null;const u=new URL(v,base);return /^https?:$/.test(u.protocol)?u.href:null}catch{return null}}
function badImage(u:string){const s=u.toLowerCase();return /(?:logo|favicon|sprite|avatar|profile|icon|placeholder|default[-_]?image|badge|spinner|loader|tracking|pixel|gravatar|whatsapp|facebook|instagram|youtube|linkedin|google|agent|author|portrait)/i.test(s)||/\.(?:svg|ico)(?:\?|$)/i.test(s)}
function words(s:string){return strip(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x))}
function score(a:string,b:string){const A=new Set(words(a)),B=new Set(words(b));if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return (2*hit)/(A.size+B.size)}
function isSharedUrl(raw:string){try{const u=new URL(raw);return u.pathname==='/'||u.pathname===''||u.searchParams.has('s')||/\/(?:properties|propiedades|listings?|inmuebles?|catalogo|catalog|ventas?|rentals?)\/?$/i.test(u.pathname)}catch{return true}}
async function fetchText(url:string,timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml,application/xml,text/xml,application/json;q=0.8,*/*;q=0.5','accept-language':'es-MX,es;q=0.9,en;q=0.7'}});const text=(await r.text()).slice(0,4_000_000);return{ok:r.ok,status:r.status,url:r.url||url,type:r.headers.get('content-type')||'',text}}finally{clearTimeout(t)}}
function images(html:string,base:string){const out:string[]=[];const add=(x:string)=>{const u=abs(x,base);if(u&&!badImage(u)&&!out.includes(u))out.push(u)};for(const re of [/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["'][^>]*>/gi,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["'][^>]*>/gi,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)["'][^>]*>/gi,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["'][^>]*>/gi])for(const m of html.matchAll(re))add(m[1]);for(const m of html.matchAll(/<(?:img|source)\b[^>]*?(?:data-src|data-lazy-src|data-original|src)=["']([^"']+)["'][^>]*>/gi))add(m[1]);for(const m of html.matchAll(/\bsrcset=["']([^"']+)["']/gi))for(const p of m[1].split(','))add(p.trim().split(/\s+/)[0]);for(const m of html.matchAll(/"(?:image|imageUrl|image_url|contentUrl|thumbnailUrl)"\s*:\s*"([^"]+)"/gi))add(m[1].replace(/\\\//g,'/'));return out.slice(0,20)}
function bestLink(html:string,base:string,title:string){let best:{url:string,s:number}|null=null;for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const u=abs(m[1],base);if(!u)continue;try{if(new URL(u).origin!==new URL(base).origin)continue}catch{continue}const s=score(title,`${strip(m[2])} ${decodeURIComponent(u)}`);if(s>=0.42&&(!best||s>best.s))best={url:u,s}}return best?.url||null}
async function sitemapUrls(origin:string){if(sitemapCache.has(origin))return sitemapCache.get(origin)!;const candidates=[`${origin}/sitemap.xml`,`${origin}/sitemap_index.xml`,`${origin}/wp-sitemap.xml`];const urls:string[]=[];const children:string[]=[];for(const s of candidates){try{const r=await fetchText(s,7000);if(!r.ok)continue;for(const m of r.text.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)){const u=decode(m[1]).trim();if(/sitemap/i.test(u))children.push(u);else urls.push(u)}if(urls.length||children.length)break}catch{}}for(const child of children.slice(0,12)){try{const r=await fetchText(child,7000);if(!r.ok)continue;for(const m of r.text.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)){const u=decode(m[1]).trim();if(!/sitemap/i.test(u))urls.push(u)}if(urls.length>5000)break}catch{}}const unique=[...new Set(urls)].slice(0,6000);sitemapCache.set(origin,unique);return unique}
async function resolveShared(original:string,title:string,firstHtml=''){let origin:string;try{origin=new URL(original).origin}catch{return null}if(firstHtml){const u=bestLink(firstHtml,original,title);if(u&&!isSharedUrl(u))return u}try{const r=await fetchText(`${origin}/wp-json/wp/v2/search?search=${encodeURIComponent(title)}&per_page=20`,7000);if(r.ok&&/json/i.test(r.type)){const arr=JSON.parse(r.text);let best:any=null;for(const x of Array.isArray(arr)?arr:[]){const u=String(x?.url||'');const s=score(title,`${x?.title||''} ${decodeURIComponent(u)}`);if(u&&s>=0.42&&(!best||s>best.s))best={u,s};}if(best?.u)return best.u}}catch{}try{const s=await fetchText(`${origin}/?s=${encodeURIComponent(title)}`,7000);if(s.ok){const u=bestLink(s.text,s.url,title);if(u&&!isSharedUrl(u))return u}}catch{}try{const list=await sitemapUrls(origin);let best:{u:string,s:number}|null=null;for(const u of list){const s=score(title,decodeURIComponent(u));if(s>=0.34&&(!best||s>best.s))best={u,s}}if(best?.u)return best.u}catch{}return null}
async function pool<T>(items:T[],n:number,fn:(x:T)=>Promise<void>){let i=0;const workers=Array.from({length:Math.min(n,items.length)},async()=>{while(true){const k=i++;if(k>=items.length)return;await fn(items[k])}});await Promise.all(workers)}

Deno.serve(async(req:Request)=>{
 if(req.method!=='POST')return new Response('Method not allowed',{status:405});
 const supplied=req.headers.get('x-listia-enrichment-key')||'';if(!supplied||await sha256(supplied)!==EXPECTED_HASH)return new Response('Unauthorized',{status:401});
 const body=await req.json().catch(()=>({}));const city=typeof body.city==='string'&&body.city.trim()?body.city.trim():null;const limit=Math.min(Math.max(Number(body.limit)||20,1),40);
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
 let q=sb.from('marketplace_listings').select('id,title,external_url,cover_image_url,gallery,city,features').eq('status','published').eq('visibility','public').not('external_url','is',null).or('cover_image_url.is.null,gallery.eq.[]').limit(800);if(city)q=q.eq('city',city);
 const {data,error}=await q;if(error)return Response.json({error:error.message},{status:500});
 const attempts=(r:any)=>Number(r?.features?.media_enrichment_attempts||0);const candidates=(data||[]).filter((r:any)=>String(r?.features?.media_enrichment_status||'')!=='updated'&&attempts(r)<4).sort((a:any,b:any)=>attempts(a)-attempts(b)).slice(0,limit);
 const counts=new Map<string,number>();for(const r of data||[]){const u=String((r as any).external_url||'');counts.set(u,(counts.get(u)||0)+1)}
 const result:any[]=[];
 const mark=async(row:any,status:string,extra:any={})=>{const now=new Date().toISOString(),old=row.features&&typeof row.features==='object'&&!Array.isArray(row.features)?row.features:{};const features={...old,media_enrichment_status:status,media_enrichment_at:now,media_enrichment_attempts:attempts(row)+1,...extra};await sb.from('marketplace_listings').update({features,updated_at:now}).eq('id',row.id)};
 await pool(candidates,6,async(row:any)=>{const original=String(row.external_url||'');try{let target=original;let first:any=null;try{first=await fetchText(original)}catch{}const shared=(counts.get(original)||0)>1||isSharedUrl(original);let imgs:string[]=[];if(!shared&&first?.ok&&/html|xhtml/i.test(first.type))imgs=images(first.text,first.url);if(shared||!imgs.length){const resolved=await resolveShared(original,row.title,first?.ok?first.text:'');if(resolved){target=resolved;const detail=await fetchText(resolved);if(detail.ok&&/html|xhtml/i.test(detail.type))imgs=images(detail.text,detail.url);else{await mark(row,`http_${detail.status}`,{media_resolved_url:target});result.push({id:row.id,status:`http_${detail.status}`,resolved:target});return}}}if(!imgs.length){const status=first?.status&&!first.ok?`http_${first.status}`:(shared?'needs_manual_shared_url':'no_images');await mark(row,status,{media_resolved_url:target!==original?target:null});result.push({id:row.id,status,resolved:target!==original?target:null});return}const gallery=imgs.slice(0,12),now=new Date().toISOString(),old=row.features&&typeof row.features==='object'&&!Array.isArray(row.features)?row.features:{};const features={...old,media_enrichment_status:'updated',media_enrichment_at:now,media_enrichment_attempts:attempts(row)+1,media_source_url:target,media_resolved_url:target!==original?target:null};const patch:any={cover_image_url:gallery[0],gallery,features,updated_at:now};if(target!==original&&!isSharedUrl(target))patch.external_url=target;const {error:uerr}=await sb.from('marketplace_listings').update(patch).eq('id',row.id);result.push({id:row.id,status:uerr?`update_error:${uerr.message}`:'updated',images:gallery.length,resolved:target!==original?target:null})}catch(e){const status=`fetch_error:${String(e).slice(0,100)}`;await mark(row,status);result.push({id:row.id,status})}});
 return Response.json({city,eligible:candidates.length,processed:result.length,updated:result.filter(x=>x.status==='updated').length,result});
});
