import { createClient } from 'jsr:@supabase/supabase-js@2';
const EXPECTED_HASH='e28ba70cf330106ef5328b7a02670f30eb14efff382c196d7013b5a8024c7c0f';
const UA='Mozilla/5.0 (compatible; LISTIA-MediaEnricher/6.0; +https://listiaapp.com)';
const STOP=new Set(['the','and','for','with','sale','venta','renta','property','properties','real','estate','mexico','casa','house','home','homes','departamento','apartment','condo','terreno','land','de','del','la','las','los','en','con','para','una','uno','un']);
function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha256(v:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
function decode(s:string){return String(s||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;/gi,' ')}
function strip(s:string){return decode(String(s||'').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim()}
function abs(raw:string,base:string){try{const v=decode(raw).trim();if(!v||/^(?:data|blob):/i.test(v))return null;const u=new URL(v,base);return /^https?:$/.test(u.protocol)?u.href:null}catch{return null}}
function badImage(u:string){return /(?:logo|favicon|sprite|avatar|profile|icon|placeholder|badge|spinner|loader|tracking|pixel|gravatar|whatsapp|facebook|instagram|youtube|linkedin|google|author|portrait)/i.test(u)||/\.(?:svg|ico)(?:\?|$)/i.test(u)}
function words(s:string){return strip(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x))}
function score(a:string,b:string){const A=new Set(words(a)),B=new Set(words(b));if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return(2*hit)/(A.size+B.size)}
function isShared(raw:string){try{const u=new URL(raw);return u.pathname==='/'||u.searchParams.has('s')||/\/(?:properties|propiedades|listings?|inmuebles?|catalogo|ventas?|rentals?)\/?$/i.test(u.pathname)}catch{return true}}
async function fetchText(url:string,timeout=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml,*/*;q=.5','accept-language':'es-MX,es;q=.9,en;q=.7'}});return{ok:r.ok,status:r.status,url:r.url||url,type:r.headers.get('content-type')||'',text:(await r.text()).slice(0,5_000_000)}}finally{clearTimeout(t)}}
function images(html:string,base:string){const out:string[]=[];const add=(raw:string)=>{const u=abs(raw,base);if(u&&!badImage(u)&&!out.includes(u))out.push(u)};for(const m of html.matchAll(/<(?:img|source)\b[^>]*?(?:data-src|data-lazy-src|data-original|src)=["']([^"']+)["'][^>]*>/gi))add(m[1]);for(const m of html.matchAll(/\bsrcset=["']([^"']+)["']/gi))for(const p of m[1].split(','))add(p.trim().split(/\s+/)[0]);for(const m of html.matchAll(/<meta[^>]+(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["'][^>]+content=["']([^"']+)["'][^>]*>/gi))add(m[1]);for(const m of html.matchAll(/"(?:image|imageUrl|image_url|contentUrl|thumbnailUrl)"\s*:\s*"([^"]+)"/gi))add(m[1].replace(/\\\//g,'/'));return out.slice(0,50)}
function bestLink(html:string,base:string,title:string){let best:any=null;for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const u=abs(m[1],base);if(!u)continue;try{if(new URL(u).origin!==new URL(base).origin)continue}catch{continue}const s=score(title,`${strip(m[2])} ${decodeURIComponent(u)}`);if(s>=.42&&(!best||s>best.s))best={u,s}}return best?.u||null}
async function resolve(original:string,title:string,first:any){if(!isShared(original)&&first?.ok)return original;let origin='';try{origin=new URL(original).origin}catch{return original}if(first?.text){const u=bestLink(first.text,first.url||original,title);if(u&&!isShared(u))return u}try{const s=await fetchText(`${origin}/?s=${encodeURIComponent(title)}`,8000);if(s.ok){const u=bestLink(s.text,s.url,title);if(u&&!isShared(u))return u}}catch{}return original}
async function pool(items:any[],n:number,fn:(x:any)=>Promise<void>){let i=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(i<items.length){const row=items[i++];await fn(row)}}))}
Deno.serve(async(req:Request)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});const supplied=req.headers.get('x-listia-enrichment-key')||'';if(!supplied||await sha256(supplied)!==EXPECTED_HASH)return new Response('Unauthorized',{status:401});const body=await req.json().catch(()=>({})),city=typeof body.city==='string'&&body.city.trim()?body.city.trim():null,limit=Math.min(Math.max(Number(body.limit)||40,1),40);const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await sb.rpc('marketplace_media_enrichment_candidates_internal',{p_city:city,p_limit:limit});if(error)return Response.json({error:error.message},{status:500});const candidates=data||[],result:any[]=[];await pool(candidates,6,async(row:any)=>{const old=row.features&&typeof row.features==='object'&&!Array.isArray(row.features)?row.features:{},attempts=Number(old.media_enrichment_attempts||0),now=new Date().toISOString();try{const first=await fetchText(String(row.external_url));const target=await resolve(String(row.external_url),String(row.title||''),first);const page=target===row.external_url?first:await fetchText(target);const found=page.ok&&/html|xhtml/i.test(page.type)?images(page.text,page.url):[];const existing=Array.isArray(row.gallery)?row.gallery.map(String):[];const merged=[...new Set([row.cover_image_url,...existing,...found].filter(Boolean).map(String))].filter(u=>!badImage(u)).slice(0,50);const features={...old,media_enrichment_status:merged.length>=20?'complete':(merged.length?'partial':'no_images'),media_enrichment_at:now,media_enrichment_attempts:attempts+1,media_source_url:target};const patch:any={features,updated_at:now};if(merged.length){patch.cover_image_url=merged[0];patch.gallery=merged}if(target!==row.external_url&&!isShared(target))patch.external_url=target;const {error:uerr}=await sb.from('marketplace_listings').update(patch).eq('id',row.id);result.push({id:row.id,status:uerr?'update_error':'updated',images:merged.length})}catch{await sb.from('marketplace_listings').update({features:{...old,media_enrichment_status:'fetch_error',media_enrichment_at:now,media_enrichment_attempts:attempts+1},updated_at:now}).eq('id',row.id);result.push({id:row.id,status:'fetch_error',images:Array.isArray(row.gallery)?row.gallery.length:0})}});return Response.json({city,eligible:candidates.length,processed:result.length,updated:result.filter(x=>x.status==='updated').length,result})});