#!/usr/bin/env python3
"""Build the versioned LISTIA commercial HTML as a Cloudflare Worker module."""
from __future__ import annotations
import argparse, base64, json
from pathlib import Path
LANGUAGES=("es","en","fr","it","pt-BR","de","ar-AE")
CLOUDCO_FORM_ENDPOINT="https://zvzafiarwerbuoaccnoz.supabase.co/functions/v1/cloudco-investment-lead"
def validate_html(html:str)->None:
    required=["const LISTIA_COMMERCIAL_I18N_VERSION = '1.0.0';","const LISTIA_COMMERCIAL_INSTALL_VERSION = '1.0.0';","document.documentElement.dir = config.dir;","document.getElementById('accederBtn').href = 'https://app.listiaapp.com/';","document.getElementById('iosBtn').href = 'https://app.listiaapp.com/?install=ios';","document.getElementById('androidBtn').href = 'https://app.listiaapp.com/?install=android';","document.getElementById('desktopBtn').href = 'https://app.listiaapp.com/?install=desktop';","canonical.href = 'https://listiaapp.com/?lang='",'<script src="/footer-legal.js?v=1" defer></script>']
    required.extend(f'<option value="{x}">' for x in LANGUAGES);required.extend(f'hreflang="{x}" href="https://listiaapp.com/?lang={x}"' for x in LANGUAGES)
    missing=[x for x in required if x not in html]
    if missing: raise ValueError("commercial HTML validation failed; missing: "+", ".join(missing))
def validate_cloudco(html:str,footer_js:str)->None:
    required=['name="robots" content="noindex,nofollow,noarchive,nosnippet,noimageindex"','src="/cloudco-assets/logo.webp"','src="/cloudco-assets/vision.webp"','id="investmentForm"',"'/cloudco/investment-plan'",'Plan de Inversión','Aceleramos y Aumentamos tu productividad']
    missing=[x for x in required if x not in html]
    if missing: raise ValueError("CloudCo HTML validation failed; missing: "+", ".join(missing))
    if 'href="/cloudco">CloudCo</a>' not in footer_js: raise ValueError("footer attribution does not point to /cloudco")
def b64(path:Path)->str:return base64.b64encode(path.read_bytes()).decode("ascii")
def build_worker(html:str,cloudco_html:str,footer_js:str,logo_b64:str,vision_b64:str)->str:
    validate_html(html);validate_cloudco(cloudco_html,footer_js)
    robots="User-agent: *\nAllow: /\nDisallow: /cloudco\nDisallow: /cloudco/\nSitemap: https://listiaapp.com/sitemap.xml\n"
    sitemap_urls="".join(f"  <url><loc>https://listiaapp.com/?lang={x}</loc></url>\n" for x in LANGUAGES).replace("&","&amp;")
    sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+sitemap_urls+'</urlset>\n'
    return f'''// Generated from commercial sources. Do not edit this build artifact.
const HTML={json.dumps(html,ensure_ascii=False)};const CLOUDCO_HTML={json.dumps(cloudco_html,ensure_ascii=False)};const FOOTER_JS={json.dumps(footer_js,ensure_ascii=False)};const CLOUDCO_LOGO_B64={json.dumps(logo_b64)};const CLOUDCO_VISION_B64={json.dumps(vision_b64)};const CLOUDCO_FORM_ENDPOINT={json.dumps(CLOUDCO_FORM_ENDPOINT)};const ROBOTS={json.dumps(robots,ensure_ascii=False)};const SITEMAP={json.dumps(sitemap,ensure_ascii=False)};
const commonHeaders={{'x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','x-frame-options':'DENY','cross-origin-opener-policy':'same-origin'}};const cloudcoHeaders={{...commonHeaders,'x-robots-tag':'noindex, nofollow, noarchive, nosnippet, noimageindex','content-security-policy':"default-src 'self'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"}};
function response(body,status,contentType,method,extraHeaders={{}},cacheControl=null){{return new Response(method==='HEAD'?null:body,{{status,headers:{{...commonHeaders,...extraHeaders,'content-type':contentType,'cache-control':cacheControl||(status===200?'public, max-age=300':'no-store')}}}})}}function decodeBase64(v){{const b=atob(v),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}}
async function cloudcoLead(request){{const origin=request.headers.get('origin')||'';if(!['https://listiaapp.com','https://www.listiaapp.com'].includes(origin))return response(JSON.stringify({{error:'origin_not_allowed'}}),403,'application/json; charset=UTF-8','GET',cloudcoHeaders,'no-store');const ct=(request.headers.get('content-type')||'').toLowerCase();if(!ct.includes('application/json'))return response(JSON.stringify({{error:'json_required'}}),415,'application/json; charset=UTF-8','GET',cloudcoHeaders,'no-store');const body=await request.text();if(new TextEncoder().encode(body).byteLength>20000)return response(JSON.stringify({{error:'payload_too_large'}}),413,'application/json; charset=UTF-8','GET',cloudcoHeaders,'no-store');try{{JSON.parse(body)}}catch(_){{return response(JSON.stringify({{error:'invalid_json'}}),400,'application/json; charset=UTF-8','GET',cloudcoHeaders,'no-store')}}const upstream=await fetch(CLOUDCO_FORM_ENDPOINT,{{method:'POST',headers:{{'content-type':'application/json','accept':'application/json','origin':'https://listiaapp.com','x-listia-client-ip':request.headers.get('cf-connecting-ip')||'','x-listia-source':'cloudco-worker-v1','user-agent':request.headers.get('user-agent')||''}},body}});return response(await upstream.text(),upstream.status,'application/json; charset=UTF-8','GET',cloudcoHeaders,'no-store')}}
export default{{async fetch(request){{const url=new URL(request.url),method=request.method.toUpperCase();if(url.hostname==='www.listiaapp.com'){{url.hostname='listiaapp.com';return Response.redirect(url.toString(),308)}}if(url.pathname==='/cloudco/investment-plan'){{if(method==='OPTIONS')return new Response(null,{{status:204,headers:{{...cloudcoHeaders,allow:'POST, OPTIONS','cache-control':'no-store'}}}});if(method!=='POST')return new Response(null,{{status:405,headers:{{...cloudcoHeaders,allow:'POST, OPTIONS','cache-control':'no-store'}}}});return cloudcoLead(request)}}if(method!=='GET'&&method!=='HEAD')return new Response(null,{{status:405,headers:{{...commonHeaders,allow:'GET, HEAD','cache-control':'no-store'}}}});if(url.pathname==='/'||url.pathname==='/index.html')return response(HTML,200,'text/html; charset=UTF-8',method);if(url.pathname==='/footer-legal.js')return response(FOOTER_JS,200,'application/javascript; charset=UTF-8',method,{{}},'public, max-age=60, must-revalidate');if(url.pathname==='/cloudco'||url.pathname==='/cloudco/'||url.pathname==='/cloudco/index.html')return response(CLOUDCO_HTML,200,'text/html; charset=UTF-8',method,cloudcoHeaders,'private, no-store');if(url.pathname==='/cloudco-assets/logo.webp')return response(decodeBase64(CLOUDCO_LOGO_B64),200,'image/webp',method,cloudcoHeaders,'public, max-age=31536000, immutable');if(url.pathname==='/cloudco-assets/vision.webp')return response(decodeBase64(CLOUDCO_VISION_B64),200,'image/webp',method,cloudcoHeaders,'public, max-age=31536000, immutable');if(url.pathname==='/robots.txt')return response(ROBOTS,200,'text/plain; charset=UTF-8',method);if(url.pathname==='/sitemap.xml')return response(SITEMAP,200,'application/xml; charset=UTF-8',method);return response('Not Found',404,'text/plain; charset=UTF-8',method)}}}};'''
def main()->int:
    p=argparse.ArgumentParser();p.add_argument("input",type=Path);p.add_argument("output",type=Path);a=p.parse_args();html=a.input.read_text(encoding="utf-8")
    candidate=a.input.parent
    d=candidate if (candidate/"cloudco.html").exists() and (candidate/"footer-legal.js").exists() else Path(__file__).resolve().parents[1]/"commercial"
    worker=build_worker(html,(d/"cloudco.html").read_text(encoding="utf-8"),(d/"footer-legal.js").read_text(encoding="utf-8"),b64(d/"cloudco-assets"/"logo.webp"),b64(d/"cloudco-assets"/"vision.webp"));a.output.write_text(worker,encoding="utf-8");print(f"Commercial Worker build validated ({len(worker.encode('utf-8'))} bytes).");return 0
if __name__=="__main__":raise SystemExit(main())