import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'
import Stripe from 'npm:stripe@22.4.0'
import postgres from 'https://deno.land/x/postgresjs@v3.4.7/mod.js'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,DB=Deno.env.get('SUPABASE_DB_URL')!,ENV=String(Deno.env.get('LISTIA_BILLING_ENV')||'test').toLowerCase(),sql=postgres(DB,{prepare:false})
const origins=new Set(['https://app.listiaapp.com','https://listiaapp.com','https://www.listiaapp.com','https://listia-pwa.pages.dev'])
const cors=(r:Request)=>{const o=r.headers.get('origin')||'';return {'access-control-allow-origin':origins.has(o)?o:'https://app.listiaapp.com','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'authorization, apikey, content-type','vary':'Origin'}}
const json=(r:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),'content-type':'application/json','cache-control':'no-store'}})
const secret=()=>ENV==='live'?(Deno.env.get('STRIPE_RESTRICTED_KEY_LIVE')||Deno.env.get('STRIPE_SECRET_KEY_LIVE')||''):(Deno.env.get('STRIPE_RESTRICTED_KEY_TEST')||Deno.env.get('STRIPE_SECRET_KEY_TEST')||'')
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{error:'method_not_allowed'},405);try{const o=req.headers.get('origin')||'';if(o&&!origins.has(o))return json(req,{error:'origin_not_allowed'},403);const jwt=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)return json(req,{error:'unauthorized'},401);const admin=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});const {data:u,error:e}=await admin.auth.getUser(jwt);if(e||!u?.user)return json(req,{error:'unauthorized'},401);const body=await req.json().catch(()=>({})) as any,id=String(body.organization_id||'');if(!id)return json(req,{error:'organization_id_required'},400);const {data:m}=await admin.from('organization_members').select('role,status').eq('organization_id',id).eq('user_id',u.user.id).eq('status','active').maybeSingle();if(!m||!['owner','admin'].includes(String(m.role)))return json(req,{error:'billing_admin_required'},403);const [state]=await sql`select provider_customer_id from private.billing_provider_state where organization_id=${id}::uuid and provider='stripe' and environment=${ENV} limit 1`;if(!state?.provider_customer_id)return json(req,{error:'stripe_customer_not_found'},404);const sk=secret();if(!sk)return json(req,{error:'stripe_not_configured'},503);const stripe=new Stripe(sk,{apiVersion:'2026-07-29.dahlia'});const ret=origins.has(o)?o:'https://app.listiaapp.com';const portal=await stripe.billingPortal.sessions.create({customer:String(state.provider_customer_id),return_url:`${ret}/?billing=portal-return`});return json(req,{ok:true,url:portal.url})}catch(err){console.error('billing-portal-create',err);return json(req,{error:'internal_error'},500)}})
