insert into private.ai_providers(provider_key,display_name,provider_type,lifecycle_status,direct_api_available,capabilities,notes,verified_at)
values ('heygen','HeyGen','direct','verified',true,'{"avatar_video":true,"digital_twin":true,"photo_avatar":true,"video_agent":true,"video_translation":true,"lip_sync":true,"tts":true,"templates":true,"batch":true,"mcp":true}'::jsonb,'HeyGen specialist for avatar-led video, advisor digital twins with consent, multilingual video translation, precision lip-sync, TTS, templates and Video Agent. Do not use as the primary property-footage preservation editor; Runway Aleph remains the dedicated existing-footage edit candidate.',now())
on conflict (provider_key) do update set display_name=excluded.display_name,provider_type=excluded.provider_type,lifecycle_status=excluded.lifecycle_status,direct_api_available=excluded.direct_api_available,capabilities=excluded.capabilities,notes=excluded.notes,verified_at=excluded.verified_at,updated_at=now();

insert into private.ai_models(model_key,provider_key,provider_model_id,display_name,family,lifecycle_status,input_modalities,output_modalities,route_tags,capabilities,deprecation_risk) values
('heygen:avatar-v','heygen',null,'HeyGen Avatar V','heygen-avatar','verified',array['text','image','audio'],array['video','audio'],array['avatar','digital_twin','presenter','premium'],'{"requires_consent_for_real_person_clone":true,"supports_4k":true}'::jsonb,'normal'),
('heygen:avatar-iv','heygen',null,'HeyGen Avatar IV','heygen-avatar','verified',array['text','image','audio'],array['video','audio'],array['avatar','photo_avatar','digital_twin','presenter'],'{"requires_consent_for_real_person_clone":true,"supports_4k":true,"motion_prompt":true}'::jsonb,'normal'),
('heygen:video-agent','heygen',null,'HeyGen Video Agent','heygen-video-agent','verified',array['text','document','image'],array['video','audio'],array['prompt_to_video','documents','brand_kit','templates'],'{"attachments_max":20}'::jsonb,'normal'),
('heygen:video-translation-precision','heygen',null,'HeyGen Video Translation Precision','heygen-translation','verified',array['video','audio'],array['video','audio','captions'],array['translation','localization','lip_sync','voice_clone','multilingual'],'{"languages_plus":175,"precision_mode":true,"proofread_supported":true}'::jsonb,'normal'),
('heygen:lipsync-precision','heygen',null,'HeyGen Precision Lipsync','heygen-lipsync','verified',array['video','audio'],array['video'],array['lip_sync','dub','audio_replace','localization'],'{"precision_mode":true}'::jsonb,'normal'),
('heygen:starfish-voice','heygen',null,'HeyGen Starfish Voice','heygen-voice','verified',array['text'],array['audio'],array['tts','voice','multilingual','presenter'],'{}'::jsonb,'normal')
on conflict (model_key) do update set provider_model_id=excluded.provider_model_id,display_name=excluded.display_name,family=excluded.family,lifecycle_status=excluded.lifecycle_status,input_modalities=excluded.input_modalities,output_modalities=excluded.output_modalities,route_tags=excluded.route_tags,capabilities=excluded.capabilities,updated_at=now();

insert into private.ai_benchmark_cases(case_key,task_type,description,risk_level,validators,score_weights) values
('advisor_avatar_v1','avatar_video','Generate an advisor-led video only from authorized identity assets while preserving identity, voice intent and script exactly.','critical','["identity_authorization","script_exactness","face_identity_similarity","voice_match","lip_sync","unauthorized_edit_detection"]'::jsonb,'{"identity_fidelity":0.4,"script_accuracy":0.2,"lip_sync":0.15,"voice":0.1,"visual_quality":0.1,"cost":0.05}'::jsonb),
('video_translate_v1','video_translate','Translate a real-estate video while preserving meaning, names, prices, property facts, speaker identity and timing.','critical','["source_transcript_lock","names_prices_numbers","translation_accuracy","speaker_consistency","lip_sync","brand_glossary"]'::jsonb,'{"translation_accuracy":0.35,"fact_accuracy":0.25,"lip_sync":0.15,"voice":0.1,"identity":0.1,"cost":0.05}'::jsonb),
('lip_sync_v1','lip_sync','Replace or dub speech while keeping video content intact and synchronizing lips to approved audio.','high','["protected_region_diff","lip_sync","audio_match","speaker_identity","timing"]'::jsonb,'{"lip_sync":0.35,"protected_fidelity":0.3,"speaker_identity":0.15,"audio_quality":0.1,"cost":0.1}'::jsonb),
('tts_locale_v1','tts','Generate native-sounding locale-correct speech with exact script and consistent brand personality.','high','["script_exactness","locale_native_score","pronunciation","numbers_names","audio_quality"]'::jsonb,'{"script_accuracy":0.3,"native_locale":0.25,"pronunciation":0.2,"audio_quality":0.15,"cost":0.1}'::jsonb)
on conflict (case_key) do update set description=excluded.description,risk_level=excluded.risk_level,validators=excluded.validators,score_weights=excluded.score_weights,updated_at=now();

insert into private.ai_route_policies(task_type,quality_tier,strategy,primary_models,reviewer_models,fallback_models,required_validators,max_parallel,max_attempts,escalate_on_failure,notes) values
('avatar_video','q2','single_then_validate',array['heygen:avatar-iv'],array['google:gemini-3.7-flash'],array['heygen:avatar-v'],array['identity_authorization','script_exactness','face_identity_similarity','lip_sync','unauthorized_edit_detection'],1,3,true,'Default advisor/presenter avatar route. Real-person digital twins require explicit authorization/consent.'),
('avatar_video','q3','primary_review',array['heygen:avatar-v'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol'],array['heygen:avatar-iv'],array['identity_authorization','script_exactness','face_identity_similarity','voice_match','lip_sync','unauthorized_edit_detection','cross_model_visual_review'],1,4,true,'Premium advisor avatar route with independent multimodal review.'),
('avatar_video','q4','primary_multi_review',array['heygen:avatar-v'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol','anthropic:claude-opus-5'],array['heygen:avatar-iv'],array['identity_authorization','script_exactness','face_identity_similarity','voice_match','lip_sync','unauthorized_edit_detection','human_gate_when_unresolved'],2,5,true,'Critical real-person avatar route; block release if identity/authorization cannot be proven.'),
('video_translate','q2','single_then_validate',array['heygen:video-translation-precision'],array['google:gemini-3.7-flash'],array[]::text[],array['source_transcript_lock','names_prices_numbers','translation_accuracy','speaker_consistency','lip_sync','brand_glossary'],1,3,true,'Default multilingual localization. Proofread/brand glossary should be used for critical real-estate terminology and names.'),
('video_translate','q3','primary_review',array['heygen:video-translation-precision'],array['openai:gpt-5.6-sol','google:gemini-3.7-flash'],array[]::text[],array['source_transcript_lock','names_prices_numbers','translation_accuracy','speaker_consistency','lip_sync','brand_glossary','cross_model_language_review'],1,4,true,'Premium localization with independent language/fact review.'),
('lip_sync','q2','single_then_validate',array['heygen:lipsync-precision'],array['google:gemini-3.7-flash'],array[]::text[],array['protected_region_diff','lip_sync','audio_match','speaker_identity','timing'],1,3,true,'Use for dubbing/audio replacement where the visual track should otherwise remain unchanged.'),
('tts','q2','single_then_validate',array['heygen:starfish-voice'],array['google:gemini-3.7-flash'],array[]::text[],array['script_exactness','locale_native_score','pronunciation','numbers_names','audio_quality'],1,3,true,'HeyGen voice is a candidate, not the universal default. Locale-native voices and cost-efficient providers remain benchmark competitors.')
on conflict (task_type,quality_tier) do update set strategy=excluded.strategy,primary_models=excluded.primary_models,reviewer_models=excluded.reviewer_models,fallback_models=excluded.fallback_models,required_validators=excluded.required_validators,max_parallel=excluded.max_parallel,max_attempts=excluded.max_attempts,escalate_on_failure=excluded.escalate_on_failure,notes=excluded.notes,updated_at=now();

insert into private.ai_provider_runtimes(runtime_key,provider_key,execution_surface,adapter_key,enabled,credential_status,credential_secret_names,health_status,configuration)
values ('heygen:direct','heygen','heygen','heygen_api',false,'not_configured',array['HEYGEN_API_KEY'],'unknown','{"mode":"direct","auth_header":"X-Api-Key"}'::jsonb)
on conflict (runtime_key) do update set provider_key=excluded.provider_key,execution_surface=excluded.execution_surface,adapter_key=excluded.adapter_key,credential_secret_names=excluded.credential_secret_names,configuration=excluded.configuration,updated_at=now();
