insert into private.ai_models(model_key,provider_key,provider_model_id,display_name,family,lifecycle_status,input_modalities,output_modalities,route_tags,capabilities,deprecation_risk) values
('open_source_local:musetalk-1.5','open_source_local','musetalk-1.5','MuseTalk 1.5','musetalk','verified',array['video','audio','image'],array['video'],array['lip_sync','identity_preservation','low_cost','open_source'],'{"verified_via":"listia_gpu","commercial_use_candidate":true,"canonical_advisor_video":true}'::jsonb,'low'),
('open_source_local:echomimic-v2','open_source_local','echomimic-v2','EchoMimicV2','echomimic','verified',array['image','audio'],array['video'],array['avatar_video','photo_to_video','half_body','open_source'],'{"verified_via":"listia_gpu","photo_only_fallback":true,"identity_benchmark_required":true}'::jsonb,'normal')
on conflict (model_key) do update set provider_model_id=excluded.provider_model_id,display_name=excluded.display_name,family=excluded.family,lifecycle_status=excluded.lifecycle_status,input_modalities=excluded.input_modalities,output_modalities=excluded.output_modalities,route_tags=excluded.route_tags,capabilities=excluded.capabilities,deprecation_risk=excluded.deprecation_risk,updated_at=now();

insert into private.ai_provider_runtimes(runtime_key,provider_key,execution_surface,adapter_key,enabled,credential_status,credential_secret_names,health_status,configuration)
values ('open_source_local:listia_gpu','open_source_local','listia_gpu','open_media_serverless',false,'not_configured',array['LISTIA_GPU_PROVIDER_KEY'],'unknown','{"mode":"serverless","preferred_backends":["modal","runpod"],"scale_to_zero":true}'::jsonb)
on conflict (runtime_key) do update set provider_key=excluded.provider_key,execution_surface=excluded.execution_surface,adapter_key=excluded.adapter_key,credential_secret_names=excluded.credential_secret_names,configuration=excluded.configuration,updated_at=now();

insert into private.ai_route_policies(task_type,quality_tier,strategy,primary_models,reviewer_models,fallback_models,required_validators,max_parallel,max_attempts,escalate_on_failure,notes,optimization_objective) values
('lip_sync','q2','single_then_validate',array['open_source_local:musetalk-1.5'],array['google:gemini-3.7-flash'],array['heygen:lipsync-precision'],array['frame_identity','lip_sync_accuracy','unauthorized_edit_detection','temporal_consistency'],1,3,true,'Cost-first lip sync. MuseTalk on LISTIA GPU is default; HeyGen Precision is premium fallback only if the open route fails quality.','lowest_cost_passing_quality'),
('lip_sync','q3','primary_review',array['open_source_local:musetalk-1.5'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol'],array['heygen:lipsync-precision'],array['frame_identity','lip_sync_accuracy','unauthorized_edit_detection','temporal_consistency','cross_model_visual_review'],1,4,true,'Premium-reviewed lip sync still starts with MuseTalk; escalate only when quality fails.','lowest_cost_passing_quality'),
('avatar_video','q2','single_then_validate',array['open_source_local:echomimic-v2'],array['google:gemini-3.7-flash'],array['heygen:avatar-iv'],array['advisor_consent','face_identity','body_consistency','lip_sync','unauthorized_edit_detection'],1,3,true,'Photo-only advisor animation starts with EchoMimicV2. Prefer canonical real advisor video + MuseTalk whenever available. HeyGen is premium fallback.','lowest_cost_passing_quality'),
('avatar_video','q3','primary_review',array['open_source_local:echomimic-v2'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol'],array['heygen:avatar-v','heygen:avatar-iv'],array['advisor_consent','face_identity','body_consistency','lip_sync','unauthorized_edit_detection','cross_model_visual_review'],1,4,true,'High-quality photo avatar route: open model first, independent review, paid escalation only if required.','lowest_cost_passing_quality'),
('avatar_video','q4','primary_multi_review',array['open_source_local:echomimic-v2'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol','anthropic:claude-opus-5'],array['heygen:avatar-v'],array['advisor_consent','face_identity','body_consistency','lip_sync','unauthorized_edit_detection','human_gate_when_unresolved'],1,5,true,'Critical avatar route. Photo generation cannot be assumed exact; block release or require canonical real advisor video/human approval when fidelity is unresolved.','lowest_cost_passing_quality')
on conflict (task_type,quality_tier) do update set strategy=excluded.strategy,primary_models=excluded.primary_models,reviewer_models=excluded.reviewer_models,fallback_models=excluded.fallback_models,required_validators=excluded.required_validators,max_parallel=excluded.max_parallel,max_attempts=excluded.max_attempts,escalate_on_failure=excluded.escalate_on_failure,notes=excluded.notes,optimization_objective=excluded.optimization_objective,updated_at=now();