insert into private.technology_registry(technology_key,display_name,layer,decision,cost_class,license_class,self_hostable,user_visible,mobile_transparent,production_allowed,requires_external_compute,replaces_or_complements,roles,constraints,notes,verified_at) values
('openai_api','OpenAI API / GPT','ai_model','core','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['other_frontier_reasoning'],array['reasoning','structured_output','tools','vision','review','image','audio'],'{"use_cost_sensitive_model_first":true,"premium_models_escalation_only":true}'::jsonb,'Backend integration uses OpenAI API, not the consumer ChatGPT product. Use lower-cost capable models first and premium models only when validation requires escalation.',now()),
('anthropic_claude','Anthropic Claude','ai_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['openai_review','gemini_review'],array['reasoning','review','arbitration','long_context','coding'],'{"reviewer_bias":true,"premium_escalation":true}'::jsonb,'Strong independent reviewer/arbitrator. Avoid routine use when a cheaper model passes the same quality gate.',now()),
('google_gemini','Google Gemini API','ai_model','core','mixed','provider_terms',false,false,true,true,false,array['openai_multimodal','qwen_multimodal'],array['multimodal','documents','vision','video_review','structured_extraction','google_ecosystem'],'{"free_tier_non_sensitive_only":true,"paid_production_route_when_required":true}'::jsonb,'Primary multimodal candidate. Free tier is a development/benchmark optimization, not a production SLA.',now()),
('kimi','Kimi / Moonshot AI','ai_model','benchmark','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['claude_agents','openai_reasoning'],array['agents','research','long_context','coding'],'{"activate_only_if_cost_quality_wins":true}'::jsonb,'Historical LISTIA candidate for complex agents/research/coding. Add to active pool only after current API/cost/privacy benchmark.',now()),
('deepseek_api','DeepSeek API','ai_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['open_weight_deepseek','cheap_text_models'],array['reasoning','coding','classification','batch','review'],'{"cost_first_candidate":true}'::jsonb,'Low-cost textual route candidate; compare direct API with self-hosted weights at volume.',now()),
('midjourney','Midjourney','media_model','lab','subscription','provider_terms',false,false,true,false,false,array['image_creative_models'],array['creative_reference','visual_benchmark'],'{"official_automation_api_required_before_runtime":true,"no_unofficial_automation":true}'::jsonb,'Keep as manual creative benchmark/reference unless an official supported automation API is available and approved.',now()),
('runway','Runway API','media_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['seedance','veo','other_video_models'],array['video_generation','video_edit','localized_edit','repair'],'{"aleph_for_repair_not_default_generation":true,"benchmark_cost_per_accepted_output":true}'::jsonb,'Aleph is especially valuable for localized repair/editing. Premium route; not default when deterministic/open routes are enough.',now()),
('nano_banana','Google Nano Banana image family','media_model','priority_candidate','mixed','provider_terms',false,false,true,true,false,array['gpt_image','seedream'],array['image_generation','image_editing','fast_visual_iteration'],'{"authoritative_text_must_be_deterministic":true}'::jsonb,'Image/visual layer only. LISTIA renders critical text separately.',now()),
('seedance_2_5','Seedance 2.5 family','media_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['veo','runway','kling','wan'],array['video_generation','multi_reference','image_to_video','video_reference'],'{"quality_cost_benchmark_required":true,"property_fidelity_gate":true}'::jsonb,'Primary premium/reference-heavy video candidate when generation is actually required.',now()),
('seedance_2_0','Seedance 2.0 family','media_model','fallback','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['seedance_2_5'],array['video_generation','legacy_fallback'],'{"prefer_2_5_when_quality_cost_wins":true,"exact_api_variant_revalidate":true}'::jsonb,'Retain older Seedance route only if it is materially cheaper and still passes LISTIA quality thresholds.',now()),
('seedream','Seedream image family','media_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['nano_banana','gpt_image'],array['image_generation','image_editing','precision','visual_reasoning'],'{"authoritative_text_must_be_deterministic":true,"benchmark_fidelity":true}'::jsonb,'Strong image/edit candidate; critical property/advisor pixels remain protected originals.',now()),
('wan','Wan video/image family','media_model','priority_candidate','open_weight_requires_compute','open/model-specific',true,false,true,true,true,array['seedance','veo','runway'],array['video_generation','open_weight_video','cost_optimization'],'{"exact_variant_license_check":true,"serverless_first":true}'::jsonb,'Important open-weight route. Prefer serverless/scale-to-zero before permanent GPU infrastructure.',now()),
('dola','BytePlus Dola / Dola Seed','ai_model','priority_candidate','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['gemini_multimodal','qwen_multimodal'],array['multimodal_reasoning','agents','routing','media_understanding'],'{"benchmark_required":true}'::jsonb,'BytePlus multimodal reasoning/agent candidate; useful companion to Seedream/Seedance ecosystem.',now()),
('higgsfield','Higgsfield','ai_gateway','benchmark','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['direct_media_providers'],array['media_gateway','video','image','audio','reference_workflows'],'{"direct_provider_preferred_when_cheaper":true}'::jsonb,'Gateway/specialist surface. Use only where it reduces integration cost or wins accepted-output economics.',now()),
('veo','Google Veo family','media_model','fallback','pay_per_use_no_fixed_fee','provider_terms',false,false,true,true,false,array['seedance','runway'],array['premium_video','cinematic_generation','audio_video'],'{"premium_escalation":true,"cost_ceiling_required":true}'::jsonb,'Premium cinematic fallback/escalation, not default low-cost generation route.',now())
on conflict (technology_key) do update set
 display_name=excluded.display_name, layer=excluded.layer, decision=excluded.decision, cost_class=excluded.cost_class,
 license_class=excluded.license_class, self_hostable=excluded.self_hostable, user_visible=excluded.user_visible,
 mobile_transparent=excluded.mobile_transparent, production_allowed=excluded.production_allowed,
 requires_external_compute=excluded.requires_external_compute, replaces_or_complements=excluded.replaces_or_complements,
 roles=excluded.roles, constraints=excluded.constraints, notes=excluded.notes, verified_at=excluded.verified_at, updated_at=now();

insert into private.ai_providers(provider_key,display_name,provider_type,lifecycle_status,direct_api_available,capabilities,notes,verified_at)
values ('kimi','Kimi / Moonshot AI','direct','discovered',true,'{"reasoning":true,"agents":true,"long_context":true,"coding":true}'::jsonb,'Candidate from LISTIA historical architecture. Runtime remains disabled until current API, pricing, privacy and benchmark are revalidated.',null)
on conflict (provider_key) do update set display_name=excluded.display_name,provider_type=excluded.provider_type,direct_api_available=excluded.direct_api_available,capabilities=excluded.capabilities,notes=excluded.notes,updated_at=now();

insert into private.ai_provider_runtimes(runtime_key,provider_key,execution_surface,adapter_key,enabled,credential_status,credential_secret_names,health_status,configuration)
values ('kimi:direct','kimi','kimi','kimi_api',false,'not_configured',array['KIMI_API_KEY'],'unknown','{"mode":"direct"}'::jsonb)
on conflict (runtime_key) do update set provider_key=excluded.provider_key,execution_surface=excluded.execution_surface,adapter_key=excluded.adapter_key,credential_secret_names=excluded.credential_secret_names,configuration=excluded.configuration,updated_at=now();