insert into private.ai_providers(provider_key,display_name,provider_type,lifecycle_status,direct_api_available,capabilities,notes,verified_at,updated_at)
values
('cloudflare','Cloudflare Workers AI','direct','adapter_ready',true,'{"chat":true,"reasoning":true,"vision":true,"tool_use":true,"free_tier_candidate":true}'::jsonb,'LISTIA-owned Workers AI runtime. Requires dedicated LISTIA token/account; no shared product credentials.',now(),now()),
('groq','Groq','direct','adapter_ready',true,'{"chat":true,"reasoning":true,"coding":true,"low_latency":true,"free_tier_candidate":true}'::jsonb,'LISTIA-owned Groq runtime. Free-tier candidate; dedicated LISTIA API key required.',now(),now())
on conflict(provider_key) do update set display_name=excluded.display_name,provider_type=excluded.provider_type,lifecycle_status=excluded.lifecycle_status,direct_api_available=excluded.direct_api_available,capabilities=excluded.capabilities,notes=excluded.notes,verified_at=excluded.verified_at,updated_at=now();

update private.ai_providers set lifecycle_status='adapter_ready',updated_at=now() where provider_key='google' and lifecycle_status not in ('deprecated','removed');

insert into private.ai_provider_runtimes(runtime_key,provider_key,execution_surface,adapter_key,enabled,credential_status,credential_secret_names,health_status,configuration,updated_at)
values
('cloudflare:workers_ai','cloudflare','cloudflare','cloudflare_workers_ai',true,'not_configured',array['listia_cloudflare_ai_token','listia_cloudflare_account_id']::text[],'unknown','{"cost_class":"free_first","gateway":"direct_workers_ai","requires_dedicated_listia_credentials":true}'::jsonb,now()),
('groq:direct','groq','groq','groq_openai_compatible',true,'not_configured',array['listia_groq_api_key']::text[],'unknown','{"cost_class":"free_first","requires_dedicated_listia_credentials":true}'::jsonb,now()),
('google:direct','google','google','google_gemini_generate_content',true,'not_configured',array['listia_google_genai_api_key']::text[],'unknown','{"cost_class":"free_tier_candidate","requires_dedicated_listia_credentials":true,"privacy_review_required_for_private_data":true}'::jsonb,now())
on conflict(runtime_key) do update set adapter_key=excluded.adapter_key,enabled=excluded.enabled,credential_secret_names=excluded.credential_secret_names,configuration=excluded.configuration,updated_at=now();

insert into private.ai_models(model_key,provider_key,provider_model_id,display_name,family,lifecycle_status,input_modalities,output_modalities,route_tags,capabilities,cost_profile,deprecation_risk,updated_at)
values
('cloudflare:nemotron-3-120b-a12b','cloudflare','@cf/nvidia/nemotron-3-120b-a12b','Nemotron 3 Super 120B A12B on Workers AI','nemotron','verified',array['text']::text[],array['text']::text[],array['free_first','reasoning','agents','tool_use']::text[],'{"reasoning":true,"function_calling":true}'::jsonb,'{"pricing_mode":"workers_ai","free_tier_candidate":true}'::jsonb,'low',now()),
('cloudflare:gemma-4-26b-a4b-it','cloudflare','@cf/google/gemma-4-26b-a4b-it','Gemma 4 26B A4B on Workers AI','gemma','verified',array['text','image']::text[],array['text']::text[],array['free_first','vision','reasoning','tool_use']::text[],'{"reasoning":true,"vision":true,"function_calling":true}'::jsonb,'{"pricing_mode":"workers_ai","free_tier_candidate":true}'::jsonb,'low',now()),
('groq:gpt-oss-120b','groq','openai/gpt-oss-120b','GPT-OSS 120B on Groq','gpt-oss','verified',array['text']::text[],array['text']::text[],array['free_first','reasoning','coding','review']::text[],'{"reasoning":true,"coding":true}'::jsonb,'{"pricing_mode":"groq_free_or_metered","free_tier_candidate":true}'::jsonb,'low',now()),
('groq:qwen3.8-27b','groq','qwen/qwen3.8-27b','Qwen 3.8 27B on Groq','qwen','verified',array['text']::text[],array['text']::text[],array['free_first','coding','reasoning','fast']::text[],'{"reasoning":true,"coding":true}'::jsonb,'{"pricing_mode":"groq_free_or_metered","free_tier_candidate":true}'::jsonb,'low',now())
on conflict(model_key) do update set provider_model_id=excluded.provider_model_id,display_name=excluded.display_name,family=excluded.family,lifecycle_status=excluded.lifecycle_status,input_modalities=excluded.input_modalities,output_modalities=excluded.output_modalities,route_tags=excluded.route_tags,capabilities=excluded.capabilities,cost_profile=excluded.cost_profile,deprecation_risk=excluded.deprecation_risk,updated_at=now();

update private.ai_route_policies set primary_models=array['cloudflare:nemotron-3-120b-a12b','groq:qwen3.8-27b']::text[],fallback_models=array['nvidia_nemotron_3_5_lightning','google:gemini-3.7-flash','openai:gpt-5.6-luna']::text[],max_attempts=5,optimization_objective='lowest_cost_passing_quality',notes='FREE-FIRST: Cloudflare/Groq before direct/premium providers. Quality validators still required.',updated_at=now() where task_type='conversation' and quality_tier='q1';
update private.ai_route_policies set primary_models=array['cloudflare:nemotron-3-120b-a12b','groq:gpt-oss-120b']::text[],fallback_models=array['nvidia_nemotron_3_5_lightning','google:gemini-3.7-flash','openai:gpt-5.6-terra']::text[],max_attempts=5,optimization_objective='lowest_cost_passing_quality',notes='FREE-FIRST balanced conversation route with premium escalation only after free candidates.',updated_at=now() where task_type='conversation' and quality_tier='q2';
update private.ai_route_policies set primary_models=array['cloudflare:nemotron-3-120b-a12b','groq:gpt-oss-120b']::text[],fallback_models=array['google:gemini-3.7-flash','nvidia_nemotron_3_5_lightning','openai:gpt-5.6-sol']::text[],max_attempts=5,optimization_objective='best_quality_within_ceiling',notes='QUALITY-FIRST while still trying strong free candidates before premium escalation.',updated_at=now() where task_type='conversation' and quality_tier='q3';
update private.ai_route_policies set primary_models=array['cloudflare:gemma-4-26b-a4b-it','cloudflare:nemotron-3-120b-a12b']::text[],fallback_models=array['groq:gpt-oss-120b','nvidia_nemotron_3_5_lightning','openai:gpt-5.6-luna']::text[],max_attempts=5,optimization_objective='lowest_cost_passing_quality',notes='FREE-FIRST property extraction; deterministic evidence validators remain authoritative.',updated_at=now() where task_type='property_extract' and quality_tier in ('q1','q2');
