insert into private.external_rate_cards(provider_key,service_key,country_code,category,direction,unit,currency,provider_rate,pricing_mode,additive_fees,source_url,source_note,last_verified_at) values
('google','nano_banana_2_lite',null,'standard','generate','image_1k','usd',0.0336,'fixed',array['input_tokens'],'https://ai.google.dev/gemini-api/docs/pricing','Gemini 3.1 Flash Lite Image standard 1K output reference.',now()),
('google','nano_banana_2_lite',null,'batch','generate','image_1k','usd',0.0168,'fixed',array['input_tokens'],'https://ai.google.dev/gemini-api/docs/pricing','Gemini 3.1 Flash Lite Image batch 1K output reference.',now()),
('google','nano_banana_2',null,'standard','generate','image_1k','usd',0.067,'fixed',array['input_tokens'],'https://ai.google.dev/gemini-api/docs/pricing','Gemini 3.1 Flash Image standard 1K output reference.',now()),
('google','nano_banana_2',null,'batch','generate','image_1k','usd',0.034,'fixed',array['input_tokens'],'https://ai.google.dev/gemini-api/docs/pricing','Gemini 3.1 Flash Image batch 1K output reference.',now()),
('byteplus','seedream_5_lite',null,null,'generate','image','usd',0.035,'fixed',array['input_image_if_applicable'],'https://www.byteplus.com/en/product/modelark','Dola Seedream 5.0 Lite output image reference.',now()),
('byteplus','seedream_5_pro',null,null,'generate','image_le_2_36mp','usd',0.045,'fixed',array['input_images_after_first'],'https://ai.byteplus.com/en','Dola Seedream 5.0 Pro output <=2.36MP; first input image free, additional input images may cost $0.003 each.',now()),
('byteplus','seedance_2_5',null,'with_video_input','generate','million_tokens','usd',6.4,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Direct ModelArk token price; actual video cost depends on generated token consumption.',now()),
('byteplus','seedance_2_5',null,'without_video_input','generate','million_tokens','usd',10.7,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Direct ModelArk token price; actual video cost depends on generated token consumption.',now()),
('byteplus','seedance_2_0',null,'with_video_input_480_720','generate','million_tokens','usd',4.3,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Direct ModelArk token reference for 480p/720p.',now()),
('byteplus','seedance_2_0',null,'without_video_input_480_720','generate','million_tokens','usd',7.0,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Direct ModelArk token reference for 480p/720p.',now()),
('byteplus','seedance_2_0_mini',null,'with_video_input','generate','million_tokens','usd',2.1,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Lowest-cost direct Seedance 2.0 family token reference.',now()),
('byteplus','seedance_2_0_mini',null,'without_video_input','generate','million_tokens','usd',3.5,'fixed',array['resolution_and_duration_determine_tokens'],'https://www.byteplus.com/en/product/modelark','Lowest-cost direct Seedance 2.0 family token reference.',now()),
('runway','seedance2_mini',null,null,'generate','video_second','usd',0.16,'fixed',array['minimum_generation_credits'],'https://docs.dev.runwayml.com/guides/pricing/','Runway-routed Seedance 2 Mini 480p/720p: 16 credits/sec, $0.01/credit.',now()),
('telnyx','sms',null,null,'outbound','message_part','usd',null,'variable_by_country',array['carrier_fee','registration_or_sender_fees'],'https://telnyx.com/pricing/messaging','Global SMS varies by destination, sender type and carrier; actual realized provider cost is canonical.',now()),
('telnyx','voice_telephony',null,null,'inbound','minute','usd',null,'variable_by_country',array['number_type','sip_trunking','voice_api','regulatory_fees'],'https://telnyx.com/pricing/voice-api','Global inbound voice varies by number/destination and SIP rate deck.',now()),
('telnyx','voice_telephony',null,null,'outbound','minute','usd',null,'variable_by_country',array['destination','sip_trunking','voice_api','regulatory_fees'],'https://telnyx.com/pricing/voice-api','Global outbound voice varies by destination and SIP rate deck.',now())
on conflict (provider_key, service_key, country_code, category, direction, unit) do update set provider_rate=excluded.provider_rate,pricing_mode=excluded.pricing_mode,additive_fees=excluded.additive_fees,source_url=excluded.source_url,source_note=excluded.source_note,last_verified_at=excluded.last_verified_at,active=true,updated_at=now();