insert into private.ai_providers(provider_key,display_name,provider_type,lifecycle_status,direct_api_available,capabilities,notes,verified_at)
values ('pika','Pika API','gateway','verified',true,'{"video":true,"image":true,"audio":true,"music":true,"3d":true,"gateway":true,"third_party_models":true}'::jsonb,'Pika API Club gateway; evaluate as cost-efficient media gateway while preserving direct-provider adapters.',now())
on conflict (provider_key) do update set display_name=excluded.display_name,provider_type=excluded.provider_type,lifecycle_status=excluded.lifecycle_status,direct_api_available=excluded.direct_api_available,capabilities=excluded.capabilities,notes=excluded.notes,verified_at=excluded.verified_at,updated_at=now();

insert into private.ai_models(model_key,provider_key,provider_model_id,display_name,family,lifecycle_status,input_modalities,output_modalities,route_tags,capabilities,deprecation_risk)
values ('pika:pika-2.5','pika','pika/pika-2.5','Pika 2.5','pika','verified',array['text','image'],array['video'],array['video','social','ads','image_to_video','gateway'],'{"max_resolution":"1080p","best_for":["short_social","ad_clips","look_dev"]}'::jsonb,'normal')
on conflict (model_key) do update set provider_model_id=excluded.provider_model_id,display_name=excluded.display_name,family=excluded.family,lifecycle_status=excluded.lifecycle_status,input_modalities=excluded.input_modalities,output_modalities=excluded.output_modalities,route_tags=excluded.route_tags,capabilities=excluded.capabilities,updated_at=now();

update private.ai_models set display_name='Runway Aleph 2.0',provider_model_id='aleph2',route_tags=array['video_edit','localized_edit','preservation','keyframes','multi_shot'],capabilities='{"max_duration_seconds":30,"max_resolution":"1080p","keyframe_images":true,"localized_edits":true,"multi_shot":true}'::jsonb,lifecycle_status='verified',updated_at=now() where model_key='runway:aleph-2';

insert into private.ai_benchmark_cases(case_key,task_type,description,risk_level,validators,score_weights)
values ('video_edit_preserve_v1','video_edit','Edit existing real-estate footage while changing only authorized content and preserving all protected source regions.','critical','["protected_region_diff","frame_identity","property_consistency","unauthorized_edit_detection","temporal_consistency","prompt_adherence"]'::jsonb,'{"protected_fidelity":0.4,"identity_fidelity":0.2,"property_fidelity":0.2,"temporal":0.1,"cost":0.05,"latency":0.05}'::jsonb)
on conflict (case_key) do update set description=excluded.description,risk_level=excluded.risk_level,validators=excluded.validators,score_weights=excluded.score_weights,updated_at=now();

insert into private.ai_route_policies(task_type,quality_tier,strategy,primary_models,reviewer_models,fallback_models,required_validators,max_parallel,max_attempts,escalate_on_failure,notes) values
('video_edit','q2','single_then_validate',array['runway:aleph-2'],array['google:gemini-3.7-flash'],array['byteplus:seedance-2.5'],array['protected_region_diff','frame_identity','property_consistency','unauthorized_edit_detection','temporal_consistency','prompt_adherence'],1,3,true,'Default existing-video edit route. Aleph 2.0 is preferred because it is designed for localized edits that preserve unaffected footage.'),
('video_edit','q3','primary_review',array['runway:aleph-2'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol'],array['byteplus:seedance-2.5'],array['protected_region_diff','frame_identity','property_consistency','unauthorized_edit_detection','temporal_consistency','prompt_adherence','cross_model_visual_review'],1,4,true,'Premium video edit with independent multimodal review.'),
('video_edit','q4','deterministic_protected_generate',array['runway:aleph-2'],array['google:gemini-3.7-flash','openai:gpt-5.6-sol','anthropic:claude-opus-5'],array['byteplus:seedance-2.5'],array['protected_region_diff','frame_identity','property_consistency','unauthorized_edit_detection','temporal_consistency','prompt_adherence','human_gate_when_unresolved'],1,5,true,'Critical edit: protected source regions remain authoritative; block release if preservation cannot be demonstrated.')
on conflict (task_type,quality_tier) do update set strategy=excluded.strategy,primary_models=excluded.primary_models,reviewer_models=excluded.reviewer_models,fallback_models=excluded.fallback_models,required_validators=excluded.required_validators,max_parallel=excluded.max_parallel,max_attempts=excluded.max_attempts,escalate_on_failure=excluded.escalate_on_failure,notes=excluded.notes,updated_at=now();

insert into private.ai_provider_runtimes(runtime_key,provider_key,execution_surface,adapter_key,enabled,credential_status,credential_secret_names,health_status,configuration)
values ('pika:gateway','pika','pika','pika_api',false,'not_configured',array['PIKA_API_KEY'],'unknown','{"mode":"gateway"}'::jsonb)
on conflict (runtime_key) do update set provider_key=excluded.provider_key,execution_surface=excluded.execution_surface,adapter_key=excluded.adapter_key,credential_secret_names=excluded.credential_secret_names,configuration=excluded.configuration,updated_at=now();
